### ISSUE TITLE
Ticking Memory Connection | CrashReport

### ISSUE THREAD

**Issue by ApollonSys** [Y3Z0N/theabyss#1]
Forge Version: 36.2.22
Abyss Version: 2.0.0-2 1.16.5
Was Optifine Installed: Y
Was it Implemented in a huge Modpack: Y

**Describe the issue**
Ticking memory connection
Cannot Load Created World

**To Reproduce**
1. Create New World
Crash Detected

Attach Log if it's crash-related!
[crash-2022-01-04_20.56.26-server.txt](https://github.com/Y3Z0N/theabyss/files/7811552/crash-2022-01-04_20.56.26-server.txt)

**Comment by Y3Z0N** [comment]
Hello!

please go to your config folder located in .minecraft/configs 
and delete the "theabyss2.json" file and create a new world! after you created your world use the command /ta2cc 
there where some changes according to the .json config system however the mod will use .json5 in the future and this error should never happen again.

#fixed
