### ISSUE TITLE
game crash with "TheAbyss (theabyss) has failed to load correctly and invocationTargetExcepton: null"  version 0.9.5

### ISSUE THREAD

**Issue by nefriston** [Y3Z0N/theabyss#102]
### Describe the Bug

[crash-2023-08-26_23.50.52-fml.txt](https://github.com/Y3Z0N/theabyss/files/12446451/crash-2023-08-26_23.50.52-fml.txt)

### Reproduction Steps

1.start game
2.wait load
3.crash game

### Expected Result

start the game

### Operating System

Windows 11

### Mod Version

1.9.X or older

### Minecraft Version

1.19.2

### Forge Version

43.2.0 and 43.2.21

**Comment by ewdfgewfwe** [comment]
i got the same problem

**Comment by Mihaly1225** [comment]
same problem

**Comment by Sadguy1234** [comment]
Try installing geckolib for me the same thing happned but after I installed geckolib minecraft loaded

**Comment by Y3Z0N** [comment]
U dont have installed geckolib.
