### ISSUE TITLE
Blaru Planks kicking people out of the server

### ISSUE THREAD

**Issue by Miko958** [Y3Z0N/theabyss#103]
### Describe the Bug

I found an issue with The Abyss II. I have a LAN modded Minecraft server with my friend and I got randomly kicked out of the server and got this error. Originally we thought the error had to do with the host (my friend) making any motion near me other than walking or running, such as jumping or flying and I'm not receiving the packets from the host about where and what sound to play during loading terrain or after loading the terrain. However, after some testing with a couple players, we have discovered that the problem is specifically blaru planks. Before I was disconnected for the first time. I was trying out blaru planks in my building which is the cause of the issue. When the blaru planks are interacted with by the host by jumping on it, breaking it or placing it etc. Players around this interaction get disconnected with this error but not the host. But if another player interacts with the block that isn't the host, both players are kicked out in most cases. After some testing with other craftable items from blaru logs, the issue is only with the blaru planks. After I looked in the logs of the host and my logs I have seen errors that there was an error receiving a packet (probably with the sound) just before I got kicked out. I have attached the image of the error that appears when someone gets kicked out because of this issue. Is there any solution to this problem?

### Reproduction Steps

1. I have attached the mod pack used in the current version of CurseForge after updating it because we though it would fix the issue. 
2. We use Hamachi to connect the players to the LAN 
3. The bug is described in the description so it shouldn't be hard to recreate. If you need any other help with the reproduction just dm me. 
[miguel.zip](https://github.com/Y3Z0N/theabyss/files/12454890/miguel.zip)

...

### Expected Result

I don't know what to write here. However, I would expect this issue to be patched or for some steps on fixing this because this is my last resort as multiple subreddits and discord groups did not help me at all. If not I would have to find a way to remove the block so no one has issues with it on the server or another player using the block to their advantage. 

### Screenshots and Videos

![Minecraft server sound problem](https://github.com/Y3Z0N/theabyss/assets/83230646/11605d50-9abf-4380-bbda-81b053bc9dce)

### Crash Report or Log

<script src="https://gist.github.com/Miko958/77d25ad8734efeba3c7ea36f5a002075.js"></script>

### Operating System

Windows 11

### Mod Version

1.9.X or older

### Minecraft Version

1.19.2

### Forge Version

43.2.21

### Other Mods

There are 94 mods and 1 resource pack. Originally there were 5 resource packs but 4 were removed for testing as they were related to sound. The removed packs were:
- Better Zombies by creepermax123 
- Dramatic Skys by thebaum64
- Hyper realistic sky -Update: Terralith and Biomes O' Plenty support by usernamegeri
- 月舞-Sky resoucepack by 月舞

If you need the mod pack with all of those resource packs I have attached it here. Also, all the mods will show up in Curseforge so that's where you can get a full list of them. 
[probably_fixed.zip](https://github.com/Y3Z0N/theabyss/files/12455280/probably_fixed.zip)

**Comment by Y3Z0N** [comment]
lan worlds are not supported. also not caused by the abyss
