### ISSUE TITLE
Incredibly Low Crystal Spawn Rate

### ISSUE THREAD

**Issue by PedroNunezCode** [Y3Z0N/theabyss#106]
### Describe the Bug

I have been looking for frost and caverna crystals for weeks and have only found one of each. I understand that they are rare but something seemed off. I went into spectator mode with only the abyss mod loaded and flew around for about 30 minutes. I was not able to find ANY of either crystals. Is this the expected behavior? or is this a known bug?

### Reproduction Steps

N/A

### Expected Result

N/A

### Screenshots and Videos

N/A

### Crash Report or Log

N/A

### Operating System

Windows 11

### Mod Version

1.9.X or older

### Minecraft Version

1.19.2

### Forge Version

43.2.6

### Other Mods

None

### Additional Context

TA-0.9.5-1.19.2.jar

**Comment by Y3Z0N** [comment]
Fixed in 1.20.1
