### ISSUE TITLE
Config file does not generate and causes console spam.

### ISSUE THREAD

**Issue by DesolateIntention** [Y3Z0N/theabyss#108]
### Describe the Bug

The config file for the mod is not generating upon world creation or server startup. 
Additionally, an error message is generated when a player joins the server, leading to console clutter.

`[Server thread/INFO]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: java.io.FileNotFoundException: config\theabyss2.json (The system cannot find the file specified)`
The error message goes on for 25 lines.
[Full error message.](https://gist.github.com/DesolateIntention/29847143696098a73c2b4f7f36994e06)

I am using the latest version of Forge 1.16.5 and of The Abyss II 1.16.5...

> **1.16.5-forge-36.2.42**
> **TheAbyss2 2.2.3-4 1.16.5**

I am using the latest version of Windows 11.
The issue also occurs on a Mohist 1.16.5 server.

### Single-player steps.
1. Install Forge 1.16.5 and The Abyss II mod.
2. Create a new world with default parameters.

### Server steps.
1. Install Forge 1.16.5 or Mohist 1.16.5 & install The Abyss II mod.
2. Start the server.
3. Additional step, join the server to generate an error message.

### Expected Result

A config file for The Abyss II mod generates correctly in the `config` folder.
No error messages when a player joins the server.

### Crash Report or Log

https://gist.github.com/DesolateIntention/2ae78adfde57d87ada4d7e20a2715a9b

### Operating System

Windows 11

### Mod Version

2.2.2

### Minecraft Version

1.19.2

### Forge Version

36.2.42

### Other Mods

Only TheAbyss2 2.2.3-4 1.16.5.

### Additional Context

I would really appreciate if this bug could be looked into. I throughly enjoy this mod but it is preventing me from configuring it, as well as spamming my console greatly.

Thanks in advance!

**Comment by Y3Z0N** [comment]
this version isnt supported anymore

**Comment by MrRedstoneA1** [comment]
Command /ta2cc generates a config file.

**Comment by DesolateIntention** [comment]
> Command /ta2cc generates a config file.

How did a randy give me a better answer than the owner of the mod? Thanks a lot.

**Comment by MrRedstoneA1** [comment]
> > Command /ta2cc generates a config file.
> 
> How did a randy give me a better answer than the owner of the mod? Thanks a lot.

You're welcome. Sadly most mod authors abandon old versions as soon as a newer version of minecraft is out.
