### ISSUE TITLE
Dimension entirely blue, playerex not installed

### ISSUE THREAD

**Issue by june012006** [Y3Z0N/theabyss#11]
Playing on modpack allthemagic spellbound and the entirety of the abyss dimension is blue, nothing visible.    Playerex is not part of the modpack, which I understand to be a common cause of the issue.

**Comment by Y3Z0N** [comment]
try to update you graphic driver and set your settings to fancy. also try it without using optifine. 
however 1.9.X versions are not supported here on github and it seems Spellbound uses the old version

**Comment by Y3Z0N** [comment]
no response.
#closed
