### ISSUE TITLE
Minable tag is replaced or changed by the mod causing no pickaxe able to mine blocks that need pickaxes

### ISSUE THREAD

**Issue by TysonNguyen619** [Y3Z0N/theabyss#111]
### Describe the Bug

As simple as above 

### Reproduction Steps

I'm just playing and it happens suddenly, ever since then it happens on every world i created after (for testing ofc)

### Expected Result

I fixed it by installing the mod "Load my fucking tags" and it also helps to notify your mod having the issue, can't play without the mod rn without this problem occuring imo (maybe can but i'm too tired to try it lol)

### Screenshots and Videos

The mod show the error caused in the latest.log here 
![Abyss error](https://github.com/Y3Z0N/theabyss/assets/150374817/71d8728b-88cb-4198-b234-f77638859b36)

### Crash Report or Log

https://gist.githubusercontent.com/TysonNguyen619/76faea617b5f66c2fe985dd830e4dc67/raw/a0763186141f37016be2ec6fba3cccd56b7fb6e9/gistfile1.txt

### Operating System

Window 10

### Mod Version

1.9.X or older

### Minecraft Version

1.19.2

### Forge Version

47.2.32

### Other Mods

I think your mod is the main issue tho

### Additional Context

Version of the mod is TATOS 1.0.5_beta and minecraft version is 1.20.1 (i can't change it up there so i submit here)

**Comment by uhloin** [comment]
I confirm the same issue for 1.20.1
After upgrade from "TATOS 1.0.1_stable.jar" to "TATOS 1.0.5_beta.jar" I started a new game and cannot mine stone -> cobblestone with wooden pickaxe.

**Comment by ilan10000** [comment]
i can confirm too and it was the first time playing the mod so i searched the whole internet for how to break it

**Comment by Y3Z0N** [comment]
Im aware of this issue :) thats why it says 
"
    beta stage
    do not use until stable release.
"

It is fixed InDev. please use 1.0.1 and wait for a stable 1.0.5 release

**Comment by Luna-Nocturna** [comment]
A heads up: Downgrading from 1.0.5 to 1.0.1 causes existing world/saves to have a datapack conflict and enforce safe mode or resolve it manually.
