### ISSUE TITLE
2.2.0 Anti infection recipe not working

### ISSUE THREAD

**Issue by DragonKiller952** [Y3Z0N/theabyss#12]
### Describe the Bug

whenever I try to create anti infection essence with 4 rotten flesh, it gives me immortal substance instead

### Reproduction Steps

1. use somnium infuser
2. put 4 abyss rotten flesh, 1 somnium and 1 loran energy in the infuser

### Expected Result

I expected to get anti infection essence, since that is what the recipe says

### Operating System

MacOS, Windows 10

### Mod Version

2.0.0-4

### Minecraft Version

1.16.5

### Forge Version

36.2.20

**Comment by Y3Z0N** [comment]
fixed in 2.2.0-1
