### ISSUE TITLE
Ability to translate item descriptions etc.

### ISSUE THREAD

**Issue by LDsanya** [Y3Z0N/theabyss#15]
### Describe the Suggestion

Hi developers, thanks for the cool mod is very exciting and challenging. I understand that this is not a priority but please as will be able to add to the localization file lines from the description of items and workbenches from the mod. Thank you for your work and good luck in developing and promoting the project.

### Screenshots and Videos

![E](https://user-images.githubusercontent.com/46693585/150544195-75102a77-1afe-4f12-9b0a-063f2243e950.jpg)

**Comment by Y3Z0N** [comment]
we‘ll working on this

**Comment by Y3Z0N** [comment]
im still working on it :-) just that you know but im currently focusing on 1.18.X Port

**Comment by Y3Z0N** [comment]
feature was added to 1.19.2 closed for now merging russia translation in 14 days
