### ISSUE TITLE
Guide book not loading properly

### ISSUE THREAD

**Issue by cordemia** [Y3Z0N/theabyss#16]
Hi. I'm playing on a Better Minecraft multiplayer server, and crafted the guide book item in hopes of figuring out how to access the Abyss proper. However, opening it shows the following error message:

![2022-01-24_15 48 20](https://user-images.githubusercontent.com/72937978/150862985-702c481a-8ffd-4ed2-855f-fae80681f9f1.png)
> Error building entry theabyss:flora/loran
> Error while loading entry theabyss:flora/loran page 1
> Failure parsing state matcher
> Unknown block type 'theabyss: loranflower' at position 0: <--[HERE]
> **Check your log for more**

And while some pages load and are readable, others show just a blank cube texture.
![2022-01-24_15 48 36](https://user-images.githubusercontent.com/72937978/150863634-a85f3f76-7181-4948-b43a-ce6599592e62.png)
![2022-01-24_15 54 42](https://user-images.githubusercontent.com/72937978/150863638-cf515456-99a7-48dc-9708-ec9403558e8b.png)

I assume this is probably a casualty of being on a modded multiplayer server— I haven't tested it in singleplayer yet.

Below are more details.

- Multiplayer server running Better Minecraft v52, Minecraft 1.16.5
- Other players accessed the Abyss through the radio before I did, I wasn't the first to
- I have never experienced 'dreams' when sleeping; if others did, they didn't mention it. Only learned it was supposed to happen when searching wiki about my current problem

- Pages that don't load properly (block texture):
- - Instructions: "Ch I - Dreams" & "Ch II - Loran"
- - Flora: "Loran" pg 2 (first page loads right)
- - Somnium: "Somnium" & "Somnium Extractor"

- Pages that do load properly:
- - Flora: "Loran" pg 1 (second page doesn't load)
- - Somnium: "Somnium Infuser" (all pages)

- All other pages are still locked as I have not made much progress yet (for obvious reasons). 
- Was able to read the parts that actually loaded perfectly fine without translation letter; crafted it anyway to see if that fixed anything, but no change.

LMK if you need any more information. Github won't let me add it to this post, but I have saved a copy of the log file if needed.

Thanks!

**Comment by Y3Z0N** [comment]
Update to 2.2.0 and tell me if your issue still is there

**Comment by rogue-pothos** [comment]
Having this same issue on 2.2.0-4 1.16.5 (and TA2 beginning 1.0.9 1.16.5?)  Running a CurseForge All the Magic: Spellbound server, added the /ta2cc command server side, and client side. What else can I do to remedy this? TIA!

**Comment by marsfriend** [comment]
> Update to 2.2.0 and tell me if your issue still is there

I made a single-player world with only The Abyss, Patchouli, and some inconsequential QOL mods to test it, and everything worked fine— "The Other Side" book in my inventory upon first spawn, the dreams, guide book entries loading, etc... So the issue is probably with the server needing to update or possibly conflicts between the many mods. I'll look into those further. Thanks for your time.
