### ISSUE TITLE
Rendering issue if graphics settings are not on fast preset

### ISSUE THREAD

**Issue by RurouniDonut** [Y3Z0N/theabyss#17]
### Describe the Bug

Hello, for some reason the abyss wont render properly if the graphics preset isn't on fast. I tried messing with individual settings but not else would fix it besides setting the main graphics preset to fast

### Reproduction Steps

1. Go into the Abyss
2. Set graphics preset to Fancy or Fabulous
3.
...

### Expected Result

The Abyss wont render and no blocks or mobs will be visible

### Screenshots and Videos

![2022-01-25_09 43 27](https://user-images.githubusercontent.com/2947985/150998949-7bf9b720-6a5d-4055-afb2-872f06589deb.png)
![2022-01-25_09 43 35](https://user-images.githubusercontent.com/2947985/150998951-1a109bc8-50e3-4d3e-bb0f-30fd0693ad39.png)

### Crash Report or Log

https://mclo.gs/IEE3LjW

### Operating System

Windows 10

### Mod Version

2.0.0-4

### Minecraft Version

1.16.5

### Forge Version

36.2.23

**Comment by Y3Z0N** [comment]
do you use optifine? and did you updated OpenGL? Do you use the mod PlayerEx?

**Comment by RurouniDonut** [comment]
I don't use PlayerEx or Optifine. Do I update OpenGL through Minecraft or my gpu drivers?

**Comment by Y3Z0N** [comment]
GPU

**Comment by Y3Z0N** [comment]
does it work for you?

**Comment by Y3Z0N** [comment]
#closed
reason: no answer
