### ISSUE TITLE
Crystal cutter bug or W.I.P ?

### ISSUE THREAD

**Issue by LDsanya** [Y3Z0N/theabyss#18]
### Describe the Bug

I don't know if it's a bug or W.I.P., but crystal catter doesn't cut crystals. Already have recipes for rings and upgrades, but there is no way to slice the necessary crystals.

### Reproduction Steps

1.Take any crystal and loran energy
2. Put crystal and energy into the crystal cutter
3.A cutting sound is heard, energy and crystals are consumed, but no shards are created
...

### Expected Result

Crystals should be sliced

### Operating System

Windows 10

### Mod Version

2.0.0-4

### Minecraft Version

1.16.5

### Forge Version

36.2.22

**Comment by Y3Z0N** [comment]
not a bug.
you need to research each crystal in the research table first.
#closed
