### ISSUE TITLE
Somnium Upgrade (Cooldown) does not craft (mod version 2.2.1)

### ISSUE THREAD

**Issue by LDsanya** [Y3Z0N/theabyss#19]
### Describe the Bug

can not create a can with Somnium Upgrade (Cooldown)

### Reproduction Steps

1. put all reagents in Somnium Infuser 
2. no reaction
3.
...

### Expected Result

Creating a Somnium Upgrade (Cooldown)

### Operating System

Windows 10

### Mod Version

2.0.0-4

### Minecraft Version

1.16.5

### Forge Version

36.2.22

**Comment by Y3Z0N** [comment]
fixed in 2.2.2
