### ISSUE TITLE
No Bug: but a Kind-ThankYou for opening this up

### ISSUE THREAD

**Issue by SteamDoge9000** [Y3Z0N/theabyss#2]
while the source code may remain closed source, this can still be used as an issue tracker and idk if it was someone else, me or a collecive that lead to this, but I share my thanks and to those for makign this as this mod continues to develop

thank you

**Comment by Y3Z0N** [comment]
the code will be open source when it is in a perfect state since its a full code rewrite of the old abyss mod which was made with mcreator 2 years ago. 

also: no problem its easier to manage.
