### ISSUE TITLE
Abyss Rendering Issue

### ISSUE THREAD

**Issue by RurouniDonut** [Y3Z0N/theabyss#21]
### Describe the Bug

Hello, for some reason the abyss wont render properly if the graphics preset isn't on fast. I tried messing with individual settings but not else would fix it besides setting the main graphics preset to fast. I do have the latest Nvidia drivers.

I posted this a couple days ago but I wasnt able to respond in time and so it got closed

### Reproduction Steps

1. Go into the Abyss
2. Set Graphics to Fancy or Fabulous
3.
...

### Expected Result

The Abyss wont render and no blocks or mobs will be visible

### Screenshots and Videos

![2022-01-25_09 43 27](https://user-images.githubusercontent.com/2947985/151453172-0e135a57-fdbb-40c9-b01f-42c808bf81d2.png)
![2022-01-25_09 43 35](https://user-images.githubusercontent.com/2947985/151453174-1c8f04ea-de3d-4963-902e-2408303809a3.png)

### Crash Report or Log

https://mclo.gs/IEE3LjW

### Operating System

Windows 10

### Mod Version

2.2.2

### Minecraft Version

1.16.5

### Forge Version

36.2.23

### Additional Context

One odd thing is that the Abyss does render correctly when you sleep the first two times and you're teleported temporarily.

**Comment by Y3Z0N** [comment]
since this seems to happen on just a few users I'll add a render setting in the next update.

**Comment by Y3Z0N** [comment]
can you try this with abyss standalone installed?

**Comment by KillerParticles** [comment]
This is happening to me and I can't play the mod cus of this.

**Comment by BetterDexTer** [comment]
> can you try this with abyss standalone installed?

Hello, what would be the route to get to the first image of the post in the mod files?
Or at least the name of that image within the mod files.
I have found similar ones like "loadingscreen" or "time_travel" but not the one shown in the first image of this post.
Please
