### ISSUE TITLE
crystal cutter doesn't give a output

### ISSUE THREAD

**Issue by atomic-slav69** [Y3Z0N/theabyss#25]
### Describe the Bug

so the problem that im having is that the crystal cutter consumes loran energy and they crystals to make crystal shards but no crystal shards are outputted

### Reproduction Steps

1. place the crystal cutter
2. put loran enegy in the crystal cutter
3. put any type of abyss mod crystal inside of it
4. it takes the crystals but you got 0 crystal shards

### Expected Result

to get crystal shards for crafting rings

### Operating System

Windows 10

### Mod Version

2.2.2

### Minecraft Version

1.16.5

### Forge Version

36.2.20

**Comment by Y3Z0N** [comment]
Closed. See #18
