### ISSUE TITLE
[QUESTION] How to counter infection?

### ISSUE THREAD

**Issue by Terra-B-Welch** [Y3Z0N/theabyss#28]
I noticed the moment I enter the abyss dimension I get hit with an infection that kills me after some time in the abyss, just out of nowhere, how do I counter it apart from just leaving every couple minutes?

The wiki seems too barebones atm to give any insight on this, so I'm asking it here.

**Comment by Y3Z0N** [comment]
anti infection essence check the JEI recipes

**Comment by Terra-B-Welch** [comment]
So I'm just supposed to rush that essence somehow in like the two minutes I get in the abyss dimension?
