### ISSUE TITLE
"INFECTION"

### ISSUE THREAD

**Issue by ELAPOX2** [Y3Z0N/theabyss#29]
### Describe the Bug

when I'm in the abyss for like 5 min i start dying, from what i thing is the infection around my screen, the guide book recipe is not working and doesn't appears when i go into Creative, i do have Patchiuli installed but it still doesnt work, created new world and still nothing, i cant find info about the world anywhere and how to stop the infection

### Reproduction Steps

1.go into abyss
2.after few min you will get something around screen
3.will start to die enless you leave the abyss
...

### Expected Result

a solution to getting around the infection and also fix the crafting of the book

### Screenshots and Videos

![book](https://user-images.githubusercontent.com/98757657/151818586-0103bcc3-c83f-4b7d-b858-4e56419d7883.PNG)
![2](https://user-images.githubusercontent.com/98757657/151818611-b75ff7f4-436f-4295-9939-bfc36a14d338.PNG)
![3](https://user-images.githubusercontent.com/98757657/151818622-fe9fafed-4eb1-45da-ad15-a42f96f8c0a4.PNG)

### Operating System

windows 10

### Mod Version

2.2.2

### Minecraft Version

1.16.5

### Forge Version

1.16.5

**Comment by ELAPOX2** [comment]
I have found a way around the "infection" by making aint infection essence but had to do way to much research to find out how and its hard to make, the guide book is still broken

**Comment by Y3Z0N** [comment]
sadly im a single developer working on the whole mod. we already have someone who makes the book but this may take some time

**Comment by Terra-B-Welch** [comment]
Oh? So the whole insta-infection thing when entering the abyss is a bug then? Should I just cheat in the anti-infection stuff in until this is fixed?

**Comment by ELAPOX2** [comment]
> sadly im a single developer working on the whole mod. we already have someone who makes the book but this may take some time

the mod is amazing keep up the good work, i didnt know you are the only one working on the mod, you have done a great job thank you for making it, slowly finding out how to do things with out the book Ty for the reply, hope to see updates for 1.16.5 :)

**Comment by ELAPOX2** [comment]
> Oh? So the whole insta-infection thing when entering the abyss is a bug then? Should I just cheat in the anti-infection stuff in until this is fixed?

i dont think its a bug but i think it happens a bit to quickly, first you need an somnium extractor, then make a somnium infuser, you are going to need a couple incorythe Gems to make somium and also the aint infection essence. if you have questions ill answer if i know to do them. was trying to figure this out for a few hours lol

**Comment by Terra-B-Welch** [comment]
> > Oh? So the whole insta-infection thing when entering the abyss is a bug then? Should I just cheat in the anti-infection stuff in until this is fixed?
> 
> i dont think its a bug but i think it happens a bit to quickly, first you need an somnium extractor, then make a somnium infuser, you are going to need a couple incorythe Gems to make somium and also the aint infection essence. if you have questions ill answer if i know to do them. was trying to figure this out for a few hours lol

All that in like the two minutes it gives you? Talk about demanding, having to rush all this when the mod hardly tells you anything leaves me with a bit of a negative opinion on it. Even with having an emerald jetpack from iron jetpacks I can't cover too much ground in the abyss before having to nope out, I can't imagine how it must be like for those who are just playing vanilla + abyss.

**Comment by Y3Z0N** [comment]
time for the infection will be increased. 10-15 mins until it starts to hurt. it also will not do damage each tick after that making it noon friendly.

**Comment by Y3Z0N** [comment]
rebalanced in 2.2.3
