### ISSUE TITLE
current config system migration to standerd (common) Config system

### ISSUE THREAD

**Issue by Shibva** [Y3Z0N/theabyss#3]
### Describe the Suggestion

durring my time, I have found that this mods config system is a bit ususual comapred ot the others that Ihave seen, mostly that its data from its json are stored in the player data wihin the level.dat 

this can pose some issues, such as one bug being mechoned by another in the comments (that used to exist) about existing worlds not being able to have their configs take proper effect. from my investigation, this is due to the values that were set by the config method your mod is currently ussing not updating those values in the level.dat or is failing todo so, thus resulting in the bug of config changes not loading when edited on only existing worlds

by migrating this sytem to the more tadeonal one you can do the following (and you may learn some things that you might not know, idk tbh)

Unique world config: Server configs appear to be what this is, and even recently I learned that if one wishes for these server configs to stay uniform though ought then its as simple as dragging the desired server config into the defaultConfig folder

Client Config: this can be were certain client based changes can be made, some of them may require a game restart while others can take effect, this can be were its more easier for someone todo thing like manage certain UI Elements to their liking rather than having to restart the game each time to see what changes are made

Common Config: this should be were (I think) common elements of the mod are taken place where its not meant for server or client

By also adapting to this format, mods like Create (with its config viewing system) and Configured can be used to adjust them just like people were able todo in game back in older forge game versions (your current system is unable todo this since its using a JSON format when mods that do this only read TOML files

I believe by migrating your config system to this that this can increase the configurability while at the same time making it easier todo so and at the same time eliminate some other issues that may arise when using the current config system (such as what I mentioned at the beginning)

Ik that this may take some time todo, but imo, this would be worth the time and effort

### Additional Context

I hope that this can be done and is planned, I bet some users that play this mod would appreciate it being more configurable in this sense

Additionally, you can even add small descriptions to what each setting does when given the correct format to describe what each setting does

this mod looks great and I cant wait to see more; if I was able to I would defiantly give you a coffee

**Comment by Y3Z0N** [comment]
will be added once we're done with the 1.18 port

**Comment by DavyCricket** [comment]
I can't find the config at all. Where is it located?

**Comment by Y3Z0N** [comment]
added in 1.19.2 closed
