### ISSUE TITLE
Fear Effect being applied to not just the Abyss dimensions

### ISSUE THREAD

**Issue by PyroBurnem** [Y3Z0N/theabyss#31]
### Describe the Bug

As the title says. You are able to be scared in dimensions other than the Abyss dimensions.

### Reproduction Steps

1. Install the latest version of The Abyss
2. Install any mod that adds dimensions. The one I'm using is the Twilight Forest, also on the latest version.
3. Join a game and go to the Twilight Forest dimension and wait

### Expected Result

To not be scared while in the Twilight Forest

### Operating System

Windows 10

### Mod Version

2.2.2

### Minecraft Version

1.16.5

### Forge Version

36.2.23

**Comment by Y3Z0N** [comment]
could not reproduce this issue but will look into it again.

**Comment by Y3Z0N** [comment]
no answer since 7 days
closed
