### ISSUE TITLE
[SUGGESTION] Add forge tags to abyss ore variants.

### ISSUE THREAD

**Issue by Terra-B-Welch** [Y3Z0N/theabyss#32]
### Describe the Suggestion

The abyss has its own variants of iron, gold and diamond, why not add these to the forge ore tags for better mod compatibility?

### Screenshots and Videos

n/a

### Additional Context

Common ores for dimension mods use tags for their ores, especially when they have variants of vanilla ores like this. Iron uses forge:ores/iron while gold uses forge:ores/gold and diamond uses forge:ores/diamond. It wouldn't hurt to adapt the abyss ores to this for better compatibility.

**Comment by Y3Z0N** [comment]
if we use tags then other mods could override those variants. that's actually out of scope to add tags for ore variants

**Comment by Terra-B-Welch** [comment]
I added the tags with crafttweaker and never noticed any issues. 🤷‍♀️

**Comment by Y3Z0N** [comment]
added
