### ISSUE TITLE
Only crimson and abyss crystals are able to be gotten in 2.2.0 when mining crystals

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [Y3Z0N/theabyss#33]
### Describe the Bug

While watching toAsgaard's latest episode, he is only getting crimson and abyss crystals when mining the crystals in the abyss dimension. I think he either used the alfsteel aiot or a diopside pickaxe. 

### Reproduction Steps

Haven't checked this myself personally. 

### Expected Result

Crystals to give their respective color when mined. 

### Operating System

Windows?

### Mod Version

2.2.2

### Minecraft Version

1.16.5

### Forge Version

36.2.20

### Other Mods

ATM Spellbound 2.2.3

**Comment by Y3Z0N** [comment]
invalid! Check 2.2.2
