### ISSUE TITLE
Why aren't the changes from the githab added to the new version?

### ISSUE THREAD

**Issue by LDsanya** [Y3Z0N/theabyss#35]
### Describe the Suggestion

Hi author, thanks for your work. Tell me please, why in the new version did not move the translation and did not add  loot tables for enchanting loot?

**Comment by Y3Z0N** [comment]
2.2.3 is the actually release version. this GitHub is for version 2.4.0 :) that's why its not included in that release yet

**Comment by LDsanya** [comment]
ок

**Comment by Y3Z0N** [comment]
will let you know once it comes out i still work on a few features, rebalances and fixes :-)
