### ISSUE TITLE
More of a question than a suggestion.

### ISSUE THREAD

**Issue by JeezyOG** [Y3Z0N/theabyss#4]
### Describe the Suggestion

I have abyss 20 beta on my server and have seen he new release version. I don't know for sure but I think I remember somewhere saying updating from beta to a release would require a world reset. We have the config generated however nobody has actually visited the abyss yet. would we be bale to update or would a new world be required?

**Comment by Y3Z0N** [comment]
you should be able to update safely if you are on beta 20
