### ISSUE TITLE
abyss mod crashes 

### ISSUE THREAD

**Issue by DKLYNTLY** [Y3Z0N/theabyss#42]
### Describe the Bug

when u load a world the game crashes and generates this log [https://gist.github.com/DarklyNightly/b5907da406e559f8409ec54f01207738](https://www.minecraftforum.net/linkout?remoteUrl=https%253a%252f%252fgist.github.com%252fDarklyNightly%252fb5907da406e559f8409ec54f01207738)

### Reproduction Steps

1. you download v3.1 from here https://www.curseforge.com/minecraft/modpacks/modded-oneblock-skyblock/files
2. press play
3. create a void world
...

### Expected Result

i expect to load in and get to play the modpack

### Crash Report or Log

https://gist.github.com/DarklyNightly/b5907da406e559f8409ec54f01207738

### Operating System

Macos Monterey 12.2.1

### Mod Version

2.2.2

### Minecraft Version

1.16.5

### Forge Version

36.2.28

### Other Mods

[1.16.5]Gender-1.8.0.jar
[Forge] Wildfire Female Gender Mod-2.8.jar
acceleratorcraft-1.2.1.jar
AdditionalEnchantedMiner-1.16.5-16.1.11.jar
AdvancementPlaques-1.16.5-1.4.1.jar
Afterlight v2.0.jar
AI-Improvements-1.16.5-0.4.0.jar
allthemodium-1.5.18-1.16.5-36.1.23.jar
AnimalCrops-1.16.5-0.6.1.jar
Apotheosis-1.16.5-4.8.4.jar
archers_paradox-1.16.5-1.4.0.1.jar
architectury-1.30.53.jar
Artifacts-1.16.5-2.10.4.jar
astralsorcery-1.16-1.16.5-1.13.12.jar
AttributeFix-1.16.5-10.1.3.jar
Atum-1.16.5-2.2.10.jar
AutoRegLib-1.6-49.jar
Avaritia_furnace-2.2.1-1.16.5.jar
avaritialite-1.5.0-1.16.5.jar
BasicNetherOres-1.16.5-5.5.0.jar
BetterAdvancements-1.16.5-0.1.1.115.jar
BetterBurning-1.16.5-6.0.6.jar
bettercompat-0.4.1-1.16.5-36.2.20.jar
BetterDiving-1.16.5-1.3.4.jar
betterendforge-1.16.5-1.6.3.jar
BetterF3-1.1.3-forge-1.16.5.jar
betterweather-2.0.1.jar
BiomesOPlenty-1.16.5-13.1.0.477-universal.jar
blame-1.16.5-3.7.0-forge.jar
BloodMagic-1.16.4-3.1.7-27.jar
blue_skies-1.16.5-1.1.3.jar
Bookshelf-Forge-1.16.5-10.4.31.jar
Botania-1.16.5-420.2.jar
bountifulbaubles-1.16.5-0.1.0-forge.jar
BrandonsCore-1.16.5-3.0.12.240-universal.jar
cabletiers-1.16.5-0.544.jar
caelus-forge-1.16.5-2.1.3.2.jar
carryon-1.16.5-1.15.5.22.jar
champions-forge-1.16.5-2.0.1.8.jar
Chisel-MC1.16.5-2.0.1-alpha.4.jar
chocolate-1.3.0-1.16.4.jar
chunkloaders-1.1.10-mc1.16.jar
citadel-1.8.1-1.16.5.jar
ClientTweaks_1.16.3-5.3.0.jar
Clumps-6.0.0.27.jar
CodeChickenLib-1.16.5-4.0.6.443-universal.jar
cofh_core-1.16.5-1.4.2.9.jar
collective-1.16.5-4.7.jar
compactmachines-4.0.0-beta.2.jar
CompactVoidMiners-B1.16.5-1.18.jar
constructionwand-1.16.5-2.6.jar
controlled_oneblock-1.0.0.jar
Controlling-7.0.0.28.jar
convenientcurioscontainer-1.2-1.16.5.jar
CosmeticArmorReworked-1.16.5-v4a.jar
Creative-Tweaker-Alpha-1.0.0.jar
Crimson-Chickens-1.16.5-1.0.10.jar
Crimsons-Crate-1.16.5-1.0.2.jar
CTM-MC1.16.1-1.1.2.6.jar
Cucumber-1.16.5-4.1.12.jar
curioofundying-forge-1.16.5-5.2.0.0.jar
curios-forge-1.16.5-4.0.8.0.jar
Curious Armor Stands-1.16.5-2.1.2.jar
curiouselytra-forge-1.16.5-4.0.2.4.jar
curiousshulkerboxes-forge-1.16.5-4.0.1.0.jar
Cyclic-1.16.5-1.5.13.jar
CyclopsCore-1.16.5-1.12.1.jar
DarkUtilities-1.16.5-8.0.10.jar
dimdungeons-1.13.1.jar
Ding-1.16.5-1.3.0.jar
Disenchanting-forge-1.16.5-1.7.2.jar
Draconic-Evolution-1.16.5-3.0.20.440-universal.jar
Draconic-Machinery_1.0.0-Beta_1.16.5.jar
DungeonsArise-1.16.5-2.1.47-release.jar
DungeonsMod-1.16.3-1.4.43.jar
EasyMagic-v1.0.4-1.16.5.jar
elevatorid-1.16.5-1.7.13.jar
emcbaubles-1.16.5-1.2.1.jar
EmendatusEnigmatica-1.2.15-build.7+mc1.16.5.jar
EnchantingInfuser-v1.0.2-1.16.5-Forge.jar
EnchantmentDescriptions-1.16.5-7.0.18.jar
enderchests-1.16-1.7.9.jar
EnderStorage-1.16.5-2.8.0.168-universal.jar
endertanks-1.16-1.9.8.jar
endportalrecipe_1.16.5-2.5.jar
enhancedcelestials-2.0.9-1.16.5.jar
ensorcellation-1.16.5-1.4.1.2.jar
entityculling-forge-mc1.16.5-1.5.0.jar
EvilCraft-1.16.5-1.1.14.jar
ExNaturae-1.16.4-1.0.4.jar
exnihiloauto-1.16-1.2.0.1.jar
exnihilomekanism-1.16-1.0.0.1.jar
exnihilosequentia-1.16-20220205-012521.jar
exnihilothermal-1.16-1.0.0.0.jar
exnihilotinkers-1.16-1.0.0.0.jar
expandability-2.0.1-forge.jar
ExponentialPower-2.0.1.jar
ExtraBotany-r1.2-68.jar
extradisks-1.16.4-1.5.1.jar
extragolems-16.5.2.jar
fakeblocks-1.16.5-1.0.1.jar
fastbenchminusreplacement-1.4.jar
fastfurnaceminusreplacement-1.1-1.16.3.jar
FastLeafDecay-v25.2.jar
ferritecore-2.1.0-forge.jar
fixedanvilrepaircost_1.16.5-1.6.jar
FluxNetworks-1.16.5-6.2.1.14.jar
forge-branders-spawnermod-1.16.5-1.8.14.jar
forgery-1.16-1.4.0_01.jar
FpsReducer-forge-1.24-mc1.16.5.jar
ftb-backups-2.1.2.2.jar
ftb-industrial-contraptions-1605.1.3-build.122.jar
ftb-library-forge-1605.3.4-build.90.jar
FunMod 5.3.jar
gardenofglass-1.7.jar
geckolib-forge-1.16.5-3.0.65.jar
getittogetherdrops-1.16.5-v1.1.1.jar
glassential-forge-1.16.5-1.1.7.jar
Gobber2-Forge-1.16.5-2.3.53.jar
goblintraders-1.6.0-1.16.3.jar
goprone-1.16.4-1.3.5.jar
HammerLib-1.16.5-16.3.27.jar
iceandfire-2.1.9-1.16.5.jar
Iceberg-1.16.5-1.0.38.jar
ImmersiveEngineering-1.16.5-5.0.7-143.jar
ImmersivePetroleum-1.16.5-3.3.0-11.jar
Industrial Agriculture[Botania]-1.16.5-1.7.2.jar
Industrial Agriculture[Core]-1.16.5-1.8.15.jar
Industrial Agriculture[Gobber]-1.16.3-1.7.1.jar
Industrial Agriculture[Industrial Foregoing]-1.16.3-1.7.1.jar
Industrial Agriculture[Mekanism]-1.16.3-1.7.1.jar
Industrial Agriculture[Powah]-1.16.3-1.7.1.jar
Industrial Agriculture[Silent's Mechanisms]-1.16.5-1.8.10.jar
industrial-foregoing-1.16.5-3.2.14.6-14.jar
infernal-expansion-1.16.5-2.4.0.jar
InsaneLib-1.4.2-mc1.16.5.jar
InventoryEssentials_1.16.5-2.3.2.jar
inventorypets-1.16.5-2.0.15.jar
inzheFoPCore-v.1.2.0.jar
ironchest-1.16.5-11.2.21.jar
ironfurnaces-1.16.5-2.7.7.jar
IronGenerators-1.6.0-final-1.16.x.jar
IronJetpacks-1.16.5-4.2.3.jar
ItemLocks-1.16.5-1.2.jar
JAOPCA-1.16.5-3.4.3.25.jar
jei-1.16.5-7.7.1.150.jar
jeiintegration_1.16.5-7.0.1.15.jar
journeymap-1.16.5-5.7.3.jar
JustEnoughProfessions-1.16.5-1.2.2.jar
JustEnoughResources-1.16.5-0.12.1.133.jar
KleeSlabs_1.16.5-9.2.1.jar
kryptonreforged-mc1.16.5_v1.0.0.jar
lazydfu-0.1.3.jar
LegendaryTooltips-1.16.5-1.1.6.jar
lemonlib-1.3.6.jar
LibX-1.16.3-1.0.76.jar
Login_Shield-1.16.5-5-g909ffa8.jar
Lollipop-1.16.5-3.2.9.jar
lootbagmod-1.16.5-2.4.0.jar
LostTrinkets-1.16.5-0.1.27.jar
mahoutsukai-1.16.5-v1.34.7.jar
managear-1.16.3-2.2.3.jar
Mantle-1.16.5-1.6.157.jar
mcjtylib-1.16-5.1.4.jar
Mekanism-1.16.5-10.1.1.456.jar
MekanismAdditions-1.16.5-10.1.1.456.jar
MekanismGenerators-1.16.5-10.1.1.456.jar
MekanismTools-1.16.5-10.1.1.456.jar
mermaidtail-1.4b.jar
metalbarrels-1.16.2-3.3b.jar
minecraft-comes-alive-7.0.8-forge.jar
MinecraftMod 1_16_4 Catch Enty Ball.jar
mining_dimension-1.16.5-1.0.6.jar
miniutilities-1.2.3.jar
mob_grinding_utils-1.16.5-0.4.32.jar
mobcatcher-1.16.4-3.2a.jar
MoreChickens-1.16.5-1.1.2.3.jar
morevanillalib-1.16.4-1.4.1.jar
morevillagers-FORGE-1.16.5-1.5.5.jar
morezombievillagers_1.16.5-1.4.jar
Morph-o-Tool-1.4-27.jar
MouseTweaks-2.14-mc1.16.2.jar
mowziesmobs-1.5.22.jar
MutantBeasts-1.16.4-1.1.3.jar
mutantmore-1.16.5-1.0.0.jar
myrtrees-forge-1.0.19.jar
MysticalAgradditions-1.16.5-4.2.4.jar
MysticalAgriculture-1.16.5-4.2.6.jar
Nameless Trinkets-1.16.5-1.1.2.jar
NaturesCompass-1.16.5-1.9.1-forge.jar
netherite-plus-mod-1.4.5-1.16.5-forge.jar
NetherPortalFix_1.16.3-7.2.1.jar
NoFog-1.2.0_1.16.5-forge.jar
nohostilesaroundcampfire_1.16.5-3.8.jar
notenoughcrashes-4.1.4+1.16.5-forge.jar
NourishedEndV6.1 Backport.jar
NourishedNetherV10ProperBackport.jar
observerlib-1.16.5-1.5.3.jar
Omega Craft 4.3.5.jar
oneblock-1.16.x-1.6.0.jar
opchanter-1.16.4-2.0.0.jar
OptiFine_1.16.5_HD_U_G8.jar
OreExcavation-1.8.157.jar
outvoted-1.16.5-1.2.4.jar
Overloaded-1.16.5-0.0.97.jar
overloadedarmorbar-5.1.0.jar
Patchouli-1.16.4-53.2.jar
pedestals-0.8s_hotfix_5.jar
Penguin-Lib-1.16.5-0.4.3.jar
PickleTweaks-1.16.5-5.2.6.jar
PiTweaks-1.16.5-1.3.3.jar
Placebo-1.16.5-4.6.1.jar
polymorph-forge-1.16.5-0.39.jar
portality-1.16.5-3.2.5.jar
Powah-1.16.5-2.3.16.jar
powerfultotems-1.16.5-1.0.jar
prefab-1.6.5.15.jar
productivebees-1.16.5-0.6.9.25.jar
ProgressiveBosses-3.4.3-mc1.16.5.jar
Project_MMO-1.16.5-3.67.5.jar
ProjectE-1.16.5-PE1.0.1B.jar
projecte-integration-1.16.5-4.3.0.jar
projectex-1605.2.0-build.3.jar
ProjectExtended-1.16.5-1.2.0.jar
PuzzlesLib-v1.0.15-1.16.5-Forge.jar
Quark-r2.4-322.jar
QuarkOddities-1.16.3.jar
randomenchants-4.0.8.jar
randomium-1.16.5-1.7.jar
randompatches-2.4.4-forge.jar
rangedpumps-0.8.2.jar
rats-7.2.0-1.16.5.jar
refinedstorage-1.9.17.jar
refinedstorageaddons-0.7.4.jar
relics-0.3.4.1.jar
reliquary-1.16.5-1.3.5.1104.jar
restrictions-1.16-3.0.6.jar
rftoolsbase-1.16-2.1.2.jar
rftoolsbuilder-1.16-3.1.6.jar
rftoolscontrol-1.16-4.0.14.jar
rftoolsdim-1.16-7.0.20-beta.jar
rftoolspower-1.16-3.0.13.jar
rftoolsstorage-1.16-2.0.17.jar
rftoolsutility-1.16-3.1.10.jar
RSInfinityBooster-1.16.5-1.1+13.jar
Runelic-1.16.5-7.0.2.jar
SaveYourPets-1.16.2-1.0.0.7.jar
ScalableCatsForce-2.13.8-build-3-with-library.jar
ScalingHealth-1.16.5-4.1.5+11.jar
SereneSeasons-1.16.5-4.0.1.124-universal.jar
ServerTabInfo-1.16.4-1.3.4.jar
shetiphiancore-1.16-3.8.10.jar
Shrink-1.16.5-1.1.6.jar
shutupexperimentalsettings-1.0.3.jar
silent-gear-1.16.5-2.6.30.jar
silent-lib-1.16.3-4.9.6.jar
SilentMechanisms-1.16.3-1.0.1+77.jar
simplegens-1.16.5-3.0.9.2.jar
Simply-Seasons-1.16.5-1.0.17.jar
simplybackpacks-1.16.5-2.0.2-build.30.jar
sit-1.16.5-v1.3.1.jar
Slots-1.16.5-1.0.0.jar
smoothboot-forge-1.16.4-1.2.2.jar
SneakyMagic-v1.3.2-1.16.5.jar
SoL-Carrot-1.16.5-1.10.1.jar
sophisticatedbackpacks-1.16.5-3.15.7.531.jar
SoundFilters-0.14_for_1.16.2.jar
Space-BossTools-1.16.5-5.5e.jar
structure_gel-1.16.5-1.7.8.jar
structurescompass-1.16.5-1.3.0.jar
supermartijn642configlib-1.0.9-mc1.16.jar
supermartijn642corelib-1.0.16-mc1.16.5.jar
survivaloverhaul-1.16.5-0.4.1b.jar
swingthroughgrass-1.16.4-1.5.3.jar
switchbow-1.7.jar
TConstruct-1.16.5-3.3.3.332.jar
the_bumblezone_forge-3.2.1+1.16.5.jar
The_Undergarden-1.16.5-0.5.5.jar
theoneprobe-1.16-3.1.4.jar
thermal_cultivation-1.16.5-1.4.1.3.jar
thermal_expansion-1.16.5-1.4.2.4.jar
thermal_foundation-1.16.5-1.4.3.10.jar
thermal_innovation-1.16.5-1.4.1.3.jar
thermal_locomotion-1.16.5-1.4.1.2.jar
titanium-1.16.5-3.2.8.7-22.jar
tombstone-6.7.3-1.16.5.jar
ToolBelt-1.16.5-1.16.0.jar
topaddons-1.16.5-2.2.0-beta.jar
torchmaster-2.3.8.jar
torohealth-1.16.4-forge-4.jar
toughnessbar-6.1.jar
TravelersBackpack-1.16.5-5.4.6.jar
twilightforest-1.16.5-4.0.870-universal.jar
Ultimate SkyBlock Resource Generator-1.16.5-3.0.jar
Unique Enchantments Base-1.16.5-1.1.1.jar
Unique Enchantments Battle-1.16.5-1.1.3.jar
Unique Enchantments Utils-1.16.5-1.5.0.jar
Unique Enchantments-1.16.5-2.1.3.jar
upgradedcore-1.16.5-1.0.0.3-release.jar
upgradednetherite_creative-1.16.5-1.0.0.4-release.jar
upgradednetherite_items-1.16.5-1.0.0.4-release.jar
upgradednetherite_ultimate-1.16.5-1.0.0.4-release.jar
upgradednetherite-1.16.5-2.0.0.8-release.jar
useless-sword-1.16.5-V1.3.7.jar
UtilitiX-1.16.3-0.1.16.jar
valkyrielib-1.16.5-3.0.9.5.jar
VampiresNeedUmbrellas-1.16.5-1.1.5.jar
Vampirism-1.16.5-1.8.6.jar
VampirismIntegrations-1.16.5-1.6.1.jar
vanillahammers-1.16.4-2.2.0.jar
VanillaTweaks-1.16.5-1.5.46.jar
VillagersRespawn-1.16.5-1.36.0.4.jar
villagertools-1.16.5-1.0.2.jar
voidworld-1.16.5-1.0.0.jar
VTweaks-1.16.4-3.5.0.jar
wandering-bag-1.16.5-1.0.4.jar
Waystones_1.16.5-7.6.4.jar
what_did_you_vote_for-1.16.5-1.0.5.jar
WitherSkeletonTweaks-1.16.5-5.4.1.jar
woot-1.16.5-1.0.8.3.jar

**Comment by DKLYNTLY** [comment]
uhh so is this gonna be ignored?

**Comment by Terra-B-Welch** [comment]
Looks like the mod creator abandoned the mod :S
