### ISSUE TITLE
easy way for get loren flower?

### ISSUE THREAD

**Issue by stormzit0** [Y3Z0N/theabyss#43]
How can I find the loren flowers?

**Comment by Zhaith-Izaliel** [comment]
I assume you are talking about the Loran Flowers.

As describe in the book you're giving upon creating a world you have to:
- Sleep twice in a bed and you'll be teleported two times in a dream dimension. (it's purely for aesthetic purposes and for immersion btw)
- After that you have to find a cabin in a forest biome and right click on the radio. It will teleport you to another dimension with only Loran Flower. 

From this you'll be able to gather them.
