### ISSUE TITLE
Add Recipes

### ISSUE THREAD

**Issue by Sybsuper** [Y3Z0N/theabyss#5]
### Describe the Suggestion

Add recipes for:
- Smelting ores in the Blast Furnace (`blasting`)
- Smelting of food in the Smoker (`smoking`)
- Crafting of stone-like slab/stair etc. in the Stonecutter (`stonecutting`)

## Example iron ingot
Original recipe (`iron_ingot_rcp.json`):
```json
{
  "type": "minecraft:smelting",
  "experience": 1,
  "cookingtime": 200,
  "ingredient": {
    "item": "theabyss:iron_variant"
  },
  "result": {
    "item": "minecraft:iron_ingot"
  }
}
```
Suggested additional recipe (`iron_ingot_from_blasting_rcp.json`):
```json
{
  "type": "minecraft:blasting",
  "experience": 1,
  "cookingtime": 100,
  "ingredient": {
    "item": "theabyss:iron_variant"
  },
  "result": {
    "item": "minecraft:iron_ingot"
  }
}
```

### List of recipes affected
_Note: These lists might be incomplete._

Stonecutting:
- cobble_stone_slab
- coble_stone_stairs
- coble_stone_wall
- stone_brick_pillar
- stone_brick
- stone_brick_slab
- stone_brick_stairs
- stone_brick_wall

Smoking:
- cooked_deer_beef
- cooked_fish

Blasting:
- gold_ingot
- iron_ingot

**Comment by Y3Z0N** [comment]
thank you! i'll add all recipes if you find some more let me know and i'll add them within the next dungeon update

**Comment by Y3Z0N** [comment]
added
