### ISSUE TITLE
Move insominum bar

### ISSUE THREAD

**Issue by LuigiTP** [Y3Z0N/theabyss#53]
### Describe the Suggestion

im not sure but is there any way i can move the somnium bar? or make it transparent?  (im in 1.16.5 btw)

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/46649309/165634172-a0c45e91-3877-4387-8f57-fa0666abad8d.png)

### Additional Context

Playing in a big modpack and most bars are transparent or only show up when needed however somnium is covering them when they do show up is it possible to do something similar?

**Comment by v1-c705** [comment]
I had the same question a while ago and found out you can move the somnium bar by playing with the x and y numbers in the config bar. Here (https://github.com/Y3Z0N/theabyss/issues/48) is the Issue I opened, there I explain how I went about it. There's also an option to make the bar invisible while you don't have any Somnium. Symilar to the way the armor bar works.

**Comment by KazukiKazuma** [comment]
Oh, also, there's an option to make the bar invisible while you don't have any Somnium. Symilar to the way the armor bar works.

**Comment by LuigiTP** [comment]
thank you very much found it 
i assume i need to restart minecraft for it to change
