### ISSUE TITLE
Bug glass cutter bug

### ISSUE THREAD

**Issue by MalleusMatias** [Y3Z0N/theabyss#55]
### Describe the Bug

When putting the necessary items to cut the crystals in the cutter, these do not give the final result, only the energy source and the crystals are spent and they do not give any item, this does not allow us to get the rings that the mod offers since for all crafts are needed

### Reproduction Steps

1.Put the glass cutter
2.Enter loran energy 
3.Enter crystals
4.When doing this the crystal cutter spends the crystals and the loran energy without giving any result

### Expected Result

The crystal cutter should deliver the parts of the crystals, in order to craft the rings offered by the mod

### Operating System

Windows 10

### Mod Version

2.0.0-4

### Minecraft Version

1.16.5

### Forge Version

36.2.35

**Comment by Y3Z0N** [comment]
you need to research the crystal in order to cut them
