### ISSUE TITLE
Config file won't generate

### ISSUE THREAD

**Issue by HugeSeb** [Y3Z0N/theabyss#56]
### Describe the Bug

Mod has been launched on different forge instalations to try and generate config file but hasnt. Lack of config file is I think the cause of another game-breaking issue im having with the rest of my modpack. 

### Reproduction Steps

1.Install the mod
2.
3.
...

### Expected Result

config generated

### Operating System

Windows 11

### Mod Version

2.2.2

### Minecraft Version

1.16.5

### Forge Version

36.2.34

### Other Mods

Reproduced with only the abyss and the abyss beginning installed

**Comment by HugeSeb** [comment]
> [31May2022 12:25:31.082] [Server thread/INFO] [STDERR/]: [net.yezon.theabyss.procedures.ReadConfigFileProcedure:executeProcedure:116]: java.io.FileNotFoundException: config\theabyss2.json (The system cannot find the file specified)

Then,

> [31May2022 12:25:31.837] [Server thread/INFO] [net.minecraftforge.common.AdvancementLoadFix/]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@4fdc5f0b

causes a tick to take over a minute and the server shuts down

**Comment by SergioFx** [comment]
I have the same issue

**Comment by Y3Z0N** [comment]
1.16.5 will have no support from now on.
please wait for the 1.18.2 / 1.19.X release

**Comment by DesolateIntention** [comment]
Anyone found a fix? If the mod can't even generate a config file, and won't get further support, is it really fair to say it's compatible with 1.16.5?

**Comment by egundersen** [comment]
**Workaround**
Load version **2.0.0-1** on Singleplayer, Generate /config/theabyss2.json
Update to **2.2.3-4** and use the same config file

**Comment by DesolateIntention** [comment]
> **Workaround** Load version **2.0.0-1** on Singleplayer, Generate /config/theabyss2.json Update to **2.2.3-4** and use the same config file

The config file still does not generate on singleplayer with version 2.0.0-1
