### ISSUE TITLE
Loot chests are empty

### ISSUE THREAD

**Issue by Dagrik4923** [Y3Z0N/theabyss#57]
### Describe the Bug

Loot chests that are generated in The Abyss Dimension are empty.
Could it be a mod conflict with Lootr?

Were using Abyss Mod Ver TheAbyss2+2.2.3-4+1.16.5

### Reproduction Steps

1. Make new world.
2. Follow steps to enter Abyss the normal way.
3. Get to generated structures in Abyss and look for chests.
4. Open Chest.
...

### Expected Result

Chest to contain loots related to Abyss.

### Screenshots and Videos

![saveee](https://user-images.githubusercontent.com/105618387/173171781-67228791-f5e9-4130-80a5-3b4e8e05a54c.png)

### Crash Report or Log

-

### Operating System

Windows 10

### Mod Version

2.2.2

### Minecraft Version

1.16.5

### Forge Version

36.2.25

### Other Mods

No crash... just empty chests.

**Comment by Y3Z0N** [comment]
not a bug. the mod is work in progress

**Comment by Y3Z0N** [comment]
not a bug just a feature that is not fully implemented (yet)

**Comment by Y3Z0N** [comment]
fixed in 1.19.2 closed
