### ISSUE TITLE
Stone drops cobble_stone when mined with silk touch

### ISSUE THREAD

**Issue by Sybsuper** [Y3Z0N/theabyss#6]
### Describe the Bug

When mining `theabyss:stone` using a Silk Touch enchanted pickaxe the block will still drop the `theabyss:cobble_stone` item. Instead of what you'd expect: `theabyss:stone`

### Reproduction Steps

1. Get a pickaxe with the Silk Touch enchantment
2. Go to the `the abyss` world
3. Mine `theabyss:stone` block
4. The block will drop `theabyss:cobble_stone` instead of the expected `theabyss:stone`

### Expected Result

At step 4: The block should drop `theabyss:stone` instead of `theabyss:cobble_stone`

### Operating System

Linux

### Mod Version

2.0.0-1

### Minecraft Version

1.16.5

### Forge Version

36.2.22

### Additional Context

**Not** tested in the latest version (tested in `2.0.0-1`), but as the StoneBlock class is still the same in `2.0.0-4` as in `2.0.0-1` I don't expect any different behavior in the newer version.

**Comment by Y3Z0N** [comment]
not really a bug but ill consider adding this

**Comment by Y3Z0N** [comment]
fixed
