### ISSUE TITLE
Houses too common and config needs some more options

### ISSUE THREAD

**Issue by Andrezinho1** [Y3Z0N/theabyss#64]
### Describe the Suggestion

from what I've been able to see of this it's a very good mod unfortunately unless you make a Minecraft world specifically to play only this then it won't mesh well even with vanilla since the beds being so common messes up the rhythm of the game this would be fine if the config was more detailed.

oh another fix would be to make the houses a bit more "abandoned" like one of those 1 dollar Detroit houses then putting the radio in some sort of basement while removing the bed entirely or even if you want make the one normal house very rare then put the radio in someplace hidden inside or if you wanted some more lovecraft vibes maybe some hidden ritual room inside the house or underground

### Additional Context

100+ modpack with several added structures and enchantments as well as mobs

**Comment by Y3Z0N** [comment]
will be fixed in 1.19.2 (1.18.2 is not supported anymore)

**Comment by Y3Z0N** [comment]
fixed in 1.19.2
