### ISSUE TITLE
Blue screen or rendering error when entering with survival mode to the abyss

### ISSUE THREAD

**Issue by Misterrubio** [Y3Z0N/theabyss#65]
### Describe the Bug

Hi, it seems that a bunch of people is having the same problem me included, and for some reason there is not a specific solution to the problem.

The bug in question is when the screen just stays blue when entering throw the portal to the abyss. Being in creative or pressing F1 in survivor lets you see but that is not the way of solving this problem. 

This happened in a server with my friends, all suffered the same problem even though we have different windows versions.

A thing important to note is that we were using a edited version of the medieval modpack and seems like deleting the mod PlayerEx fixes the problem. I would like not maintain both mods if possible, any ideas?

### Reproduction Steps

1. Create a abyss portal
2. Enter the dimension
3. Enjoy the view
...

### Expected Result

I tried different versions of both PlayerEx and Abyss 2, but to no hope. I looked for similar problems one being a render issue were the solution was making the gaphics in "fast" mode but that thread was in creative and didn't see so that was a different bug

I expected that messing with the options would let me see the dimesnion without being in creative or with F1 view.

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/46254761/177456312-fff71fca-318b-40e4-b375-7fe057831655.png)
this is the sight of a survival player without F1
![image](https://user-images.githubusercontent.com/46254761/177457382-1abe6a2c-adc8-4ce1-8743-9572c933752a.png)
this is the sight of the survival player with F1 on
![image](https://user-images.githubusercontent.com/46254761/177457424-0250e635-226e-47d9-8ea7-116363797efd.png)
and this when on crative

while the screen is in blue, the infection will begin to grow and end up killing (the infection is the only thing that we can see while in the blue screen)

### Crash Report or Log

There was no crash

### Operating System

Windows 7 and 10

### Mod Version

2.2.2

### Minecraft Version

1.16.5

### Forge Version

36.2.34

### Other Mods

There was no crash but as I mentioned I think this is a issue that has something to do with PlayerEx or just a rendering issue of Abyss II

### Additional Context

The mod had no issues with the sleep teleportations. The version of the mod is the 2.2.3-2 idk why I can't select that version. I hope we recive a answer soon, best of luck.

**Comment by Y3Z0N** [comment]
remove PlayerEX they have to fix their issues.
