### ISSUE TITLE
Slept while server rebooted, unable to rejoin

### ISSUE THREAD

**Issue by trentnbauer** [Y3Z0N/theabyss#66]
### Describe the Bug

I am recieving an internal server error when attempting to join my Better Minecraft server

### Reproduction Steps

Install Better Minecraft v57 server pack
Log in and sleep
Restart server
Player unable to join

### Expected Result

Player can join server

### Crash Report or Log

https://pastebin.com/qfQM9Zjf

### Operating System

Windows 11 for Client, Ubuntu 20 for Server

### Mod Version

2.2.2

### Minecraft Version

1.16.5

### Forge Version

36.2.35

### Other Mods

https://www.curseforge.com/minecraft/modpacks/better-mc-modpack/files/3858222

https://www.curseforge.com/minecraft/mc-mods/easier-sleeping/files/3302060 (tried removing already - no change)

**Comment by Y3Z0N** [comment]
ask Sharkie which is the maintainer of BMC
