### ISSUE TITLE
Certain items get duplicated in the JEI when trying to hide them using Crafttweaker/ItemStages.

### ISSUE THREAD

**Issue by asoshinsky** [Y3Z0N/theabyss#67]
Creating a mod restriction using the following script hides all the items from the mod except some items shown in the attachment below.

ItemStages.createModRestriction("theabyss", "Stage 3");

Then, every time I _/reload_,  the items then get duplicated in the JEI. 

Minecraft 1.16.5
TheAbyss2 2.2.3-4 1.16.5

![Screenshot 2022-07-17 225806](https://user-images.githubusercontent.com/60367873/179426333-60ee6b94-daaf-4acb-8e15-c146d1f4b3bd.png)
![Screenshot 2022-07-17 230016](https://user-images.githubusercontent.com/60367873/179426359-30bcd86b-dac1-4a79-a227-238ee9b89e3a.png)

**Comment by Y3Z0N** [comment]
will be fixed in 1.19.2 (1.18.2 is not supported anymore)

**Comment by Y3Z0N** [comment]
fixed in 1.19.2 closed
