### ISSUE TITLE
Cannot spawn Magician(1.16.5 2.2.3)

### ISSUE THREAD

**Issue by HZDZ9495** [Y3Z0N/theabyss#68]
### Describe the Bug

I was playing this mod in modpack Odyssey Craft. However I cann't find the boss Magician. There's no information about this boss on wiki. I've read the code and learned that it spawns in the blue mountain. I suppose that it might be a bug.

### Reproduction Steps

1.
2.
3.
...

### Expected Result

The boss Magician couldn't spawn.

### Operating System

Windows 10

### Mod Version

2.2.2

### Minecraft Version

1.16.5

### Forge Version

36.2.34

**Comment by Y3Z0N** [comment]
it only can spawn in rain
