### ISSUE TITLE
Random end game music playing in overworld

### ISSUE THREAD

**Issue by CraftPro** [Y3Z0N/theabyss#69]
### Describe the Bug

In the overworld, the end_game_music keeps playing randomly. Scares the hell out of you the first time! Had to download extreme sound muffler to figure out where it was coming from so I could mute it. Could be an issue with another mod.

### Reproduction Steps

1.Explore the overworld for a while
2.Music randomly starts playing
3.
...

### Expected Result

Not hearing music randomly

### Screenshots and Videos

![theabysssounds](https://user-images.githubusercontent.com/78822270/185550905-f0f9ad77-428b-4f70-955b-8d38d49af822.png)

### Operating System

Windows 10

### Mod Version

2.2.2

### Minecraft Version

1.16.5

### Forge Version

36.2.34

### Other Mods

- AI-Improvements-1.16.5-0.5.0
- alexsmobs-1.12.1
- Apotheosis-1.16.5-4.8.4
- appleskin-forge-mc1.16.x-2.4.0
- Aquaculture-1.16.5-2.1.22
- architectury-1.32.63
- astralsorcery-1.16.5-1.14.1
- AttributeFix-1.16.5-10.1.4
- AutoRegLib-1.6-49
- BetterAdvancements-1.16.5-0.1.1.115
- BetterMineshafts-Forge-1.16.4-2.0.4
- BiomesOPlenty-1.16.5-13.1.0.477-universal
- Bookshelf-Forge-1.16.5-10.4.32
- Bountiful-1.16.4-3.3.1
- bountifulbaubles-1.16.5-0.1.0-forge
- buildinggadgets-1.16.5-3.8.2
- byg-1.3.5
- caelus-forge-1.16.5-2.1.3.2
- Cataclysm-0.20
- cavebiomeapi-1.16.5-1.4.2
- cavesandcliffs-1.16.5-7.2.0
- cgm-1.2.6-1.16.5
- citadel-1.8.1-1.16.5
- Clumps-6.0.0.28
- collective-1.16.5-4.28
- colytra-forge-1.16.5-5.1.1.2
- comforts-forge-1.16.5-4.0.1.5
- configured-1.5.2-1.16.5
- constructionwand-1.16.5-2.6
- Controlling-7.0.0.28
- CookingForBlockheads_1.16.5-9.3.4
- corail_woodcutter-1.16-2.0.2
- CraftingTweaks_1.16.5-12.2.1
- CraftTweaker-1.16.5-7.1.2.511
- curioofundying-forge-1.16.5-5.2.0.0
- curios-forge-1.16.5-4.0.5.3
- Cyclic-1.16.5-1.5.17
- dankstorage-1.16.5-3.21
- dicemcpmmonbt-1.16-1.2.2
- DoggyTalents-1.16.5-2.1.15
- DungeonCrawl-1.16.5-2.3.9
- dungeons_mobs-1.16.5-1.0.10
- DungeonsArise-1.16.5-2.1.49-beta
- DungeonsMod-1.16.3-1.4.43
- eidolon-0.2.7
- EnchantmentDescriptions-1.16.5-7.0.19
- endrem-5.0.3-R-1.16.5
- enhancedcelestials-2.0.9-1.16.5
- extremeSoundMuffler-3.18_1.16.5
- FastLeafDecay-v25.2
- ferritecore-2.1.0-forge
- forbidden_arcanus-16.2.3
- ftb-library-forge-1605.3.4-build.90
- Full-Turtle-Armor-1.0.3-FORGE-MC-1.16.4-5
- geckolib-forge-1.16.5-3.0.77
- guardvillagers-1.16.5.1.2.6
- Hwyla-forge-1.10.11-B78_1.16.2
- iceandfire-2.1.9-1.16.5
- iChunUtil-1.16.5-10.6.1
- illagers_plus-1.16.4v1.7.2
- ImmersiveEngineering-1.16.5-5.0.7-143
- InsaneLib-1.4.2-mc1.16.5
- InventoryHud_[1.16.2-1.16.5].forge-3.4.1
- invtweaks-1.16.4-1.0.1
- ironchest-1.16.5-11.2.21
- jei-1.16.5-7.7.1.152
- jeiintegration_1.16.5-7.1.0.22
- JEITweaker-1.16.5-1.1.0.49
- jmi-1.16.5-0.8.1-47
- journeymap-1.16.5-5.8.5p5
- kotlinforforge-1.17.0-obf
- lootr-1.16.5-0.1.12.43
- Magic+rings+4.2++1.16.5
- Mantle-1.16.5-1.6.157
- metalbarrels-1.16.2-3.3b
- minecolonies-1.16.5-1.0.890-RELEASE
- MouseTweaks-2.14-mc1.16.2
- MutantBeasts-1.16.4-1.1.3
- mutantmore-1.16.5-1.0.1
- NaturesCompass-1.16.5-1.9.1-forge
- Neat+1.7-27
- obfuscate-0.6.3-1.16.5
- observerlib-1.16.5-1.5.3
- oculus-1.2.5
- overloadedarmorbar-5.1.0
- pamhc2crops-1.16.3-1.0.2
- pamhc2foodcore-1.16.3-1.0.2
- Patchouli-1.16.4-53.2
- Placebo-1.16.5-4.6.1
- polymorph-forge-1.16.5-0.40
- potionsmaster-0.2.2-1.16.5-36.1.0
- ProgressiveBosses-3.4.3-mc1.16.5
- Project_MMO-1.16.5-3.67.6
- PuzzlesLib-v1.0.15-1.16.5-Forge
- Quark-r2.4-322
- repurposed_structures_forge-3.4.7+1.16.5
- rubidium-0.2.7
- shutupexperimentalsettings-1.0.3
- simplemagnets-1.1.7-forge-mc1.16
- SoL-Carrot-1.16.5-1.10.1
- sophisticatedbackpacks-1.16.5-3.15.15.607
- StorageDrawers-1.16.3-8.5.2
- structure_gel-1.16.5-1.7.8
- structurize-1.16.5-1.0.392-RELEASE
- supermartijn642configlib-1.1.3-forge-mc1.16
- supermartijn642corelib-1.0.18-forge-mc1.16.5
- swingthroughgrass-1.16.4-1.5.3
- TheAbyss2 2.2.3-4 1.16.5
- the-conjurer-1.16.4-1.0.13
- tombstone-6.7.7-1.16.5
- ToolBelt-1.16.5-1.16.2
- torchmaster-2.3.8
- TrashSlot_1.16.3-12.2.1
- u_team_core-1.16.5-3.2.1.215
- Uppers-0.3.2
- valhelsia_core-16.0.15
- village-employment-1.16.5-1.4.1
- villagernames_1.16.5-3.4
- WailaHarvestability-mc1.16.x-forge-1.1.15
- WAWLA-1.16.5-8.0.9
- Waystones_1.16.5-7.6.4
- WitherSkeletonTweaks-1.16.5-5.4.1
- YungsApi-1.16.4-Forge-13

### Additional Context

May be Sophisticated Backpacks interacting with Abyss II sound/music files

**Comment by AnukWarrior** [comment]
this is infact sophisticated backpacks causeing this as the abyss end game music is also on music disc items and mobs in the overworld can spawn with backpacks with the jukebox upgrade and can infact play modded music discs there should be an option to disable this in the backpacks mod settings

**Comment by CraftPro** [comment]
Ok. Just strange that proximity volume doesn't exist when it happens. The volume of the music is the same whether the mob is 1 block away, or 100 blocks away... LOUD

**Comment by Y3Z0N** [comment]
the reason is because i use Stereo instead of Mono thats why u can hear the music with the same loudness level 200 blocks away. the real question here is why the heck is there a mod that adds jukeboxes to entities.
