### ISSUE TITLE
Config option to disable dreams

### ISSUE THREAD

**Issue by Phantom914** [Y3Z0N/theabyss#70]
### Describe the Suggestion

The dream thing is cool, but it doesn't really work with my pack. I have a bunch of other stuff already, and custom recipes. I really liked the glitch block too which I can use with Block Carpentry to make awesome blocks. Right now I'm stuck with 1.9.7 because the 2nd dream crashes, then when I went back in it put me in the dream dimension but I used a dimension cake to leave and I couldn't get back. I didn't even know what to do in the dreams. I already have another way to get Loran other than the dreams, so it would be cool if it could be disabled to use the main portal whenever. If not than that's fine, I get it.

**Comment by Y3Z0N** [comment]
will be added in 1.19.2 all other versions are not supported anymore

**Comment by Y3Z0N** [comment]
added in 1.19.2 closed
