### ISSUE TITLE
Rendering

### ISSUE THREAD

**Issue by LOLZSICKA** [Y3Z0N/theabyss#71]
### Describe the Bug

the blocks in the abyss appear black

### Reproduction Steps

Have lastest optifine installed for 1.16.5
this occured on forge 36.2.39
it could possibly be a graphics driver issue

### Expected Result

some or all blocks should apppear black

### Operating System

windows 10

### Mod Version

2.2.2

### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Other Mods

i had dragon survival, natures compass, inbetweenlands, biomes o' plenty, armor points++, apple skin, untamed wilds, and some more i cant remember

### Additional Context

Could probaly be my intel HD graphics 400

**Comment by Y3Z0N** [comment]
Optifine is not supported sorry. closed
