### ISSUE TITLE
1.18.2 Houses and config command

### ISSUE THREAD

**Issue by CommunistPord** [Y3Z0N/theabyss#72]
Abandoned houses don't spawn in 1.18.2 version of the mod, and also the commands /ta2cc and /ta2patreon both don't work. If anyone has a fix for this it would be greatly appreciated bc i loved this mod in 1.16 and i wanna play it again but i want the new terrain generation too

**Comment by HavocJupiter** [comment]
Can confirm houses do not generate in 1.18.2.

**Comment by natelovesyou** [comment]
This is clearly an abandoned mod for the time being, despite them having Patreon supporters. :( They're not responding from reports from 2+ months ago...

**Comment by Y3Z0N** [comment]
will be fixed in 1.19.2 (1.18.2 is not supported anymore)
mod is not abandones its in the middle of porting state ;)

**Comment by Y3Z0N** [comment]
fixed indev 1.19.2
