### ISSUE TITLE
CRYSTAL CUTTER MINECRAFT FORGE 1.16.5

### ISSUE THREAD

**Issue by Falconx94** [Y3Z0N/theabyss#73]
### Describe the Bug

When I want to use the crystal cutter, it does not give me the already formed crystal but it destroys it completely and it does not appear in the inventory or in the backpack and the crystal is completely spent

### Reproduction Steps

1.A
2.B
3.C
...

### Expected Result

A CRYSTAL CLEAR SHAPED

### Operating System

Windows 10

### Mod Version

2.2.2

### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Additional Context

MOD VERSION 2.2.3-4

**Comment by Y3Z0N** [comment]
you have to research crystals before cutting them using a research table ;)
