### ISSUE TITLE
disable guide book

### ISSUE THREAD

**Issue by ComeBelin** [Y3Z0N/theabyss#74]
### Describe the Bug

i test to disable the guide book but i don't understand how.
i test to create the config file with /ta2cc in game but don't succeeded
mod in 1.18.2
mod : 2.2.3-4-a 1.18.2

### Reproduction Steps

1.download on curseforge
2.launch world
3./ta2cc not found
...

### Expected Result

fail

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/48830039/192035916-a3fbbe58-a07c-4327-8e21-5eaa29fd40f8.png)

### Operating System

window 10

### Mod Version

2.2.2

### Minecraft Version

1.16.5

### Forge Version

40.1.80

**Comment by Y3Z0N** [comment]
will be fixed in 1.19.2 (1.18.2 is not supported anymore)

**Comment by Y3Z0N** [comment]
fixed indev 1.19.2
