### ISSUE TITLE
1.18.2 Texture issue

### ISSUE THREAD

**Issue by Npcfanatic21** [Y3Z0N/theabyss#75]
Win 10

MC 1.18.2

Forge 40.1.80

Mod version 2.2.3-4-a

Had found a weird texture bug with the brick stone wall and when you place 2 next to each other, theres a texture issue
![2022-09-25_21 48 07](https://user-images.githubusercontent.com/25681027/192186391-265b9cf8-6961-4111-9590-61ebed995ca9.png)

**Comment by Npcfanatic21** [comment]
Also found with the Lokus mob, the head doesn't move with the body.

![2022-09-25_22 16 48](https://user-images.githubusercontent.com/25681027/192187246-f746e247-d3bd-422c-9dc2-6659f2ba2826.png)

**Comment by Y3Z0N** [comment]
will be fixed in 1.19.2 (1.18.2 is not supported anymore)

**Comment by Y3Z0N** [comment]
fixed indev 1.19.2
