### ISSUE TITLE
[1.18.2] Frame drops in the Abyss & Scared in Creative/Spectator

### ISSUE THREAD

**Issue by Reshy** [Y3Z0N/theabyss#76]
### Describe the Bug

Getting massive frame drops in the Abyss dimension even with stuff like Rubidium and Radium, talking max 2 FPS in some places.  Likely from excessive mob spawns (Thousands of mobs and particles are spawning).

### Reproduction Steps

1.  Travel to the Abyss dimension.

### Expected Result

The frame rate shouldn't be cut down so much when in the Abyss.  Mobs and particles shouldn't be in the thousands at all times.

You shouldn't have the Scared status when in creative or Spectator, it interferes with testing.  Scared shouldn't override night vision.

### Screenshots and Videos

![2022-10-07_02 40 02](https://user-images.githubusercontent.com/2096384/194525148-1a47057b-5d86-4eed-b1c1-bce35cdb74bb.png)
![2022-10-07_02 41 36](https://user-images.githubusercontent.com/2096384/194525095-00d8fbc2-3fa5-428c-89aa-ab33bd94e292.png)
![2022-10-07_02 43 17](https://user-images.githubusercontent.com/2096384/194525177-eea63440-15e9-4dcc-babc-8edbd27209fe.png)

### Operating System

Windows 10

### Mod Version

2.2.2

### Minecraft Version

1.16.5

### Forge Version

40.1.74

### Other Mods

Many, however optimization mods did not help the issue as it can only do so much when thousands of mobs and particles are spawned at once.

**Comment by natelovesyou** [comment]
How did you even reach the Abyss in 1.18.2? I and others aren't finding abandoned houses, and the devs never reply to any reports. Also, no such structure shows up with the /locate command or the Structure Compass, and the "broken radio" isn't in JEI.

**Comment by Y3Z0N** [comment]
could not reproduce this issue got stable 300-400 fps.

**Comment by Reshy** [comment]
> 

Forcing a dimension swap via console commands.
