### ISSUE TITLE
Abandoned Houses don't exist, 1.18.2

### ISSUE THREAD

**Issue by tasqueTestified** [Y3Z0N/theabyss#77]
### Describe the Bug

So I've been trying to find an abandoned house ever since I downloaded the mod, but they're not generating. I checked a creative world with the /locate command, but there's nothing there.

### Reproduction Steps

generate world in 1.18.2 with the abyss

### Expected Result

the houses to generate

### Operating System

Windows 10

### Mod Version

2.2.2

### Minecraft Version

1.16.5

### Forge Version

40.1.84

**Comment by natelovesyou** [comment]
Confirmed. No such structure shows up with the Structure Compass or /locate command, and the "broken radio" or just "radio" doesn't show up in the Creative Mode cheat menu or in JEI. I've flown around for a long time and there's no abandoned house.
