### ISSUE TITLE
1.18.2 house missing

### ISSUE THREAD

**Issue by Blobicus** [Y3Z0N/theabyss#78]
### Describe the Bug

so from what i read the house doesnt spawn in this version so does that mean the mod is toast or i can bypass that step in the mod. It looks like all i need from the raido part is loran but i can just spawn some in if thats the case 

### Reproduction Steps

1.tried commands
2.
3.
...

### Expected Result

an answer lol

### Operating System

windows 10

### Mod Version

2.2.2

### Minecraft Version

1.16.5

### Forge Version

1.18.2

**Comment by Y3Z0N** [comment]
will be fixed in 1.19.2 (1.18.2 is not supported anymore)

**Comment by Y3Z0N** [comment]
fixed indev 1.19.2
