### ISSUE TITLE
Detail Armor Bar mod compatibility 

### ISSUE THREAD

**Issue by GrandmaPork** [Y3Z0N/theabyss#79]
### Describe the Suggestion

There’s this cool mod on curseforge that changes your armor bar to match armor your wearing. It would be really cool if you created a few sprites for the mod since I believe it allows mods to add compatibility 

### Additional Context

Mod link: https://www.curseforge.com/minecraft/mc-mods/detail-armor-bar-forge

**Comment by Y3Z0N** [comment]
out of scope for me atm
