### ISSUE TITLE
Sky remained Overworld when dreaming of The Abyss

### ISSUE THREAD

**Issue by ChadekT** [Y3Z0N/theabyss#80]
### Describe the Bug

First time install and I read the book that says to start the dream I must sleep twice. I slept the first time and entered into a dream of The Abyss yet the sky remained the sunny blue sky of the overworld. Not sure if this is a bug or just had something to do with the mod loading slow.

### Reproduction Steps

1. Go to sleep for the first time.
2.
3.
...

### Expected Result

The expected result when reproducing what might be a bug is that the sky will look like the Overworld's (sun and blue sky) instead of what should be in The Abyss.

### Screenshots and Videos

![2022-11-06_15 11 15](https://user-images.githubusercontent.com/113884631/200158815-311b1116-f335-4aa3-9a8b-4afa3c0cec39.png)

### Operating System

Windows 10

### Mod Version

2.2.2

### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Other Mods

![2022-11-06_15 14 57](https://user-images.githubusercontent.com/113884631/200158889-9f3eedc0-d02d-4183-bfe7-19e21a68a4d4.png)
![2022-11-06_15 15 09](https://user-images.githubusercontent.com/113884631/200158892-6a1afac3-11c0-49e4-8c41-660277b80ebc.png)
![2022-11-06_15 15 19](https://user-images.githubusercontent.com/113884631/200158893-66cb7837-8224-45c0-af9d-fa41cf528d9c.png)
![2022-11-06_15 15 27](https://user-images.githubusercontent.com/113884631/200158894-413b3dc7-dd65-4735-873a-1bd95dc43434.png)
![2022-11-06_15 15 33](https://user-images.githubusercontent.com/113884631/200158897-19b100a3-d971-498f-ae97-402855ceb03f.png)
![2022-11-06_15 15 41](https://user-images.githubusercontent.com/113884631/200158899-3c680656-ab64-47ef-8d3e-7ccb3f00f8c9.png)

Here's screenshots listing all the mods that I used.

### Additional Context

Update: Had the second dream and it also happened here.
![2022-11-06_15 38 19](https://user-images.githubusercontent.com/113884631/200159702-f818e821-a635-4a5d-9f11-a54b22b07fdf.png)

**Comment by GrandmaPork** [comment]
this is a shader issue, im pretty sure it doesnt happen when you actually enter the abyss

**Comment by Y3Z0N** [comment]
shader issue closed
