### ISSUE TITLE
After quitting in a dream i got stuck in the dream

### ISSUE THREAD

**Issue by lineargraph** [Y3Z0N/theabyss#81]
### Describe the Bug

After quitting and reloading a singleplayer world i got stuck in the dream and did not get teleported out. Since this is my first time playing with this mod im not sure if this is intended (and if it is, shame on you), but after reading https://github.com/Y3Z0N/theabyss/blob/1.18.2/src/main/java/net/yezon/theabyss/events/SleepEventEvent.java i think i should get teleported back out after around 30 seconds. (I'm also a bit confused why you would use commands and dynamically unregistering event handlers. Maybe those event handlers could be replaced with something like a status effect.)

### Reproduction Steps

1. Create a singleplayer world
2. Sleep
3. Wake up and wait to get teleported
4. Quit your world
5. Rejoin your world
6. Be stuck

### Expected Result

Even after rejoining a world i would expect to be able to leave the dream, either automatically on each relog, or just by persisting the remaining time in the dream.

### Operating System

linux

### Mod Version

2.2.2

### Minecraft Version

1.16.5

### Forge Version

36.2.31

**Comment by lineargraph** [comment]
Eww stalebot

**Comment by Y3Z0N** [comment]
this issue has been fixed indev (1.19.2) 1.16.X, 1.18.X are not supported anymore and don't recieve updates.
a possible workaround for your issue would be using commands
