### ISSUE TITLE
Dark blue screen entering the dimension (Unplayable)

### ISSUE THREAD

**Issue by BetterDexTer** [Y3Z0N/theabyss#82]
### Describe the Bug

When I enter the dimension it loads completely normal, without any type of crash.
When the dimension loading screen ends (about 1 sec), all you can see is that dark blue screen and the action bar at the bottom.
The only way to "remove" that blue screen and be able to see the dimension is to press F1, but in this way it is not possible to see the action bar at the bottom, therefore the experience is not enjoyable.
It would help to know the name and path to get to that dark blue background in the mod files.

### Reproduction Steps

1. Enter the portal
2. Dimension loading screen (approximately 1 second)
3. Then just see that dark blue screen
...

### Expected Result

Being able to see the dimension correctly instead of directly not being able to play in it.

### Screenshots and Videos

![2022-11-15_13 32 49](https://user-images.githubusercontent.com/115386838/202013786-8061961d-52e5-4de8-a07c-9184f439abb8.png)
![2022-11-15_13 32 56](https://user-images.githubusercontent.com/115386838/202013825-b458c3fb-b075-41f0-8958-5bdc23c638ee.png)
![2022-11-15_13 33 09](https://user-images.githubusercontent.com/115386838/202013872-105cd1fc-c0cc-4c37-9810-39693a8247e5.png)

### Crash Report or Log

None

### Operating System

Windows 10

### Mod Version

2.2.2

### Minecraft Version

1.16.5

### Forge Version

36.2.34

### Other Mods

I've seen some users with skill mods have this problem and I have a couple of these added to the better minecraft 1.16.5 mod pack.
-Everlasting Abilities
-Goki Stats

**Comment by BetterDexTer** [comment]
I would really like an answer or comment from the developer :)

**Comment by Y3Z0N** [comment]
remove PlayerEx Mod
