### ISSUE TITLE
Teleported to dream issue

### ISSUE THREAD

**Issue by ClockworkzAI** [Y3Z0N/theabyss#83]
### Describe the Bug

Teleported to dream first time world spawned to slowely cousing me to get stuck inside stone and die.
second time it crashed the game.

### Reproduction Steps

1.Sleep
2.spawn in dream world
3.things taking it time to spawn
4. die in below your spawn point

### Expected Result

Should just spawn in world with no issues this is for 1.18.2

### Crash Report or Log

https://notepad.link/share/Yn7XVzFfs8tbm5B3EyvN

### Operating System

windows 10

### Mod Version

2.2.3-4-a

### Minecraft Version

1.18.2

### Forge Version

40.1.85

### Additional Context

TheAbyss2 2.2.3-4-a 1.18.2.jar                    |TheAbyss                      |theabyss                      |2.2.34              |DONE      |Manifest: NOSIGNATURE

**Comment by Y3Z0N** [comment]
fixed indev in 1.19.2. theres no support for 1.18.2 we skipped this version.
