### ISSUE TITLE
The Abyss 2 Guidebook not craftable

### ISSUE THREAD

**Issue by GodProZEE** [Y3Z0N/theabyss#85]
### Describe the Bug

I use Patchouli and I've tried different versions of Patchouli, and I use the latest version of The Abyss 2 mod, but I can't craft the guidebook (the 4th edition one) and even in JEI it isn't craftable (I got the recipe from the internet). I tried putting the recipe to craft it anyway, but it also didn't work. 

### Reproduction Steps

1. Create new world.
2. Put crafting recipe of guidebook in crafting table.
3.
4.
...

### Expected Result

I expected to get the book to track progress.

### Operating System

Windows 10

### Mod Version

2.2.2

### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Other Mods

citadel-1.8.1-1.16.5
Hwyla-forge-1.10.11-B78_1.16.2
iceandfire-2.1.11-1.16.5
ironchest-1.16.5-11.2.21
jei-1.16.5-7.7.1.153
magnesium-1.5
Patchouli-1.16.4-53.2
twilightforest-1.16.5-4.0.870-universal

**Comment by Y3Z0N** [comment]
1.16.5 is not supported anymore

**Comment by itsdinkd** [comment]
its not craftable in 1.19.2 either.. there is no recipe
