### ISSUE TITLE
Creating a server

### ISSUE THREAD

**Issue by ultimaxdude** [Y3Z0N/theabyss#9]
### Describe the Bug

Ok so i have this problem where i get disconnected when playing on theabyss server i made and i even asked help from aternos for about 2 hours and nothing worked and it lead me to here asking to fix this so as i said we tried everything and nothing worked i was in the void for about 2 minutes not falling then loaded but no mobs moved and nothing dropped and my outer layer skin didnt show and i get disconnected about a minute after. The first message was "java.net.socketexception connection reset by peer" then "Disconnected" and then the connection reset by peer again i am now going to send my client log and server log 
my server log: https://mclo.gs/2IZ3BTq
client log: https://mclo.gs/TzlFYMc
i hope this helps and please fix this bug

### Reproduction Steps

1.idk
2.idk
3.idk
...

### Expected Result

i dont really know

### Screenshots and Videos

![image](https://user-images.githubusercontent.com/97583426/149075310-73971905-6c46-41ba-877d-5ff97d822352.png)

### Operating System

M1 Mac (and aternos?)

### Mod Version

2.0.0-4

### Minecraft Version

1.16.5

### Forge Version

36.2.20

### Other Mods

Nothing else.

**Comment by Y3Z0N** [comment]
First delete „the beginning“ on both client and server side.

second check if you are using the same version on both client and server. it seems like you are using different versions on client and server side

**Comment by ultimaxdude** [comment]
> First delete „the beginning“ on both client and server side.
> 
> second check if you are using the same version on both client and server. it seems like you are using different versions on client and server side

Ok i will try this.

**Comment by ultimaxdude** [comment]
<img width="857" alt="Screen Shot 2022-01-12 at 3 01 59 PM" src="https://user-images.githubusercontent.com/97583426/149079656-7d51ea9e-8984-4b37-a83c-eb9f8a06a29b.png">
<img width="353" alt="Screen Shot 2022-01-12 at 3 03 08 PM" src="https://user-images.githubusercontent.com/97583426/149079729-759d7d68-8933-4c53-8c08-74add50e98c5.png">

**Comment by Y3Z0N** [comment]
i tested this now 5 times and this issue never happened for me and you also don’t provided me steps to reproduce your issue.

i think maybe its an issue on aternos side idk tbh. since your log don’t tell me anything about my mod

**Comment by ultimaxdude** [comment]
> i tested this now 5 times and this issue never happened for me and you also don’t provided me steps to reproduce your issue.
> 
> i think maybe its an issue on aternos side idk tbh. since your log don’t tell me anything about my mod

do you know any other server hosting platforms you use? (that are free)
