### ISSUE TITLE
[QUESTION, 1.16.5] Some questions about the mod

### ISSUE THREAD

**Issue by Blu3M4n97** [Y3Z0N/theabyss#90]
I have some questions regarding the 1.16.5 version using 2.2.3-4 mod version.

1) After generating the config file, what are the LPM and EA modes? Enabled them to test, but see no differences.
2) How to use the Somnium upgrades (cooldown, regen, usage)? There is no info about it on the wiki page, and just drinking them while the ring is on the bar or in the left hand just gives me a message "that had no effect".
3) Is the ghost ring supposed be non craftable?

Sorry if these questions have been already answered somewhere, but I could not find them. Any help would be appreciated!

**Comment by Y3Z0N** [comment]
Use the Guide Book. i also recommend to play on 1.20.
The ring will never get a recipe in its actual state
