### ISSUE TITLE
Server Fails to start, TheAbyss fails to load correctly 

### ISSUE THREAD

**Issue by HyperFoxOne** [Y3Z0N/theabyss#92]
### Describe the Bug

When I try to start my modded server it does not work and says that TheAbyss has failed to load correctly.
I have later tried to just use the abyss, patchuoli and geckolib and that still will not work.

### Reproduction Steps

Use the same mods and start a server 

### Expected Result

I expected the server to start

### Crash Report or Log

https://paste.modularity.gg/paste/?content=https://cdn.discordapp.com/attachments/1085998071147679744/1086589760778289225/message.txt&raw=false#165

### Operating System

Windows 11

### Mod Version

1.9.X or older

### Minecraft Version

1.19.2

### Forge Version

43.2.7

### Other Mods
I have tried without using any mod and it still will not work but the crash log is from a server with all of these mods

Festive Delight (by to0pa_fr)
Enhanced Celestials - Blood, Blue, & Harvest (Super) Moons (by Corgi_Taco)
Deeper and Darker (by KyaniteMods)
Vampires Need Umbrellas (by Focamacho)
OfflineSkins (by LainMI)
Savage & Ravage (by TeamAbnormals)
Enlightened End (by MuffinsQw)
Artifacts (by ochotonida)
Polymorph (Forge) (by TheIllusiveC4)
Medieval Siege Machines (by magistu_)
Blue Skies (by ModdingLegacy)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
Just Enough Items (JEI) (by mezz)
Get It Together, Drops! (by bl4ckscor3)
Connected Glass (by SuperMartijn642)
Kiwi 🥝 (Forge) (by Snownee_)
Botania (by Vazkii)
Layered Snowfall (by SWDTeam)
YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)
Blueprint (by TeamAbnormals)
Flywheel (by jozufozu)
Item Filters (by LatvianModder)
Chunky (Forge) (by pop4959)
Knight Quest (by count_grimhart)
Sophisticated Core (by P3pp3rF1y)
Alex's Armoury (by baldmanmods)
Iron Chests (by ProgWML6)
Gateways to Eternity (by Shadows_of_Fire)
Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)
Croptopia (by thethonk)
Structures Plus II (by Qra5)
Galosphere (by orcinus73)
TerraBlender (Forge) (by TheAdubbz)
YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)
Ars Instrumentum (by Sarenor)
Simply Swords [Fabric & Forge] (by sweenuss)
Additional Structures (by XxRexRaptorxX)
Hexerei (by JoeFoxe)
FTB Quests (Forge) (by FTB)
Alex's Mobs (by sbom_xela)
Farmer's Delight (by vectorwing)
Macaw's Bridges (by sketch_macaw)
AI Improvements (by QueenOfMissiles)
Goblin Traders (by MrCrayfish)
Placebo (by Shadows_of_Fire)
Entity Collision FPS Fix (by Corgi_Taco)
YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)
Sit (by bl4ckscor3)
Mekanism (by bradyaidanc)
YUNG's API (Forge) (by YUNGNICKYOUNG)
JourneyMap Integration (by frankv_)
FastWorkbench (by Shadows_of_Fire)
YUNG's Extras (Forge) (by YUNGNICKYOUNG)
Waystones (by BlayTheNinth)
Packing Tape (by gigaherz)
Immersive Aircraft [Fabric/Forge] (by Conczin)
Macaw's Fences and Walls (by sketch_macaw)
FTB Teams (Forge) (by FTB)
Create Crafts & Additions (by MRHminer)
Simple Voice Chat (by henkelmax)
Nether Depths Upgrade (by scouter567)
Duckling (by Frogipher)
YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG)
Better Animals Plus (by cybercat5555)
Fastload (by StockiesLad)
Macaw's Furniture (by sketch_macaw)
Illagers Wear Armor (by almightytallestred)
Quark (by Vazkii)
Dungeons Plus (by ModdingLegacy)
Citadel (by sbom_xela)
Rebind Narrator (by quat1024)
Nether's Delight (by lumpazl)
spark (by Iucko)
Moonlight Lib (by MehVahdJukaar)
Rotten Creatures (by fusionstudiomc)
Thermal Foundation (by TeamCoFH)
The Twilight Forest (by Benimatic)
Macaw's Trapdoors (by sketch_macaw)
Iron Furnaces [FORGE] (by XenoMustache)
Quark Oddities (by Vazkii)
Capybara [Forge] (by TechSupportRed)
Stalwart Dungeons (by Furti_Two)
YUNG's Better Witch Huts (Forge) (by YUNGNICKYOUNG)
Connectable Minecarts (by mrtutankhamun)
Smooth Boot (Reloaded) (by AbdElAziz333)
Prism [Forge] (by Grend_G)
Domestication Innovation (by sbom_xela)
Aquaculture 2 (by Shadowclaimer)
Visual Workbench (by Fuzs)
Integrated API (by CraisinLord)
⚔️ RPG style More Weapons! (by zrikon)
Architectury API (Fabric/Forge) (by shedaniel)
Illage and Spillage (by this_is_stupid123)
Bookshelf (by DarkhaxDev)
Create: Steam 'n Rails (by mattentosh)
Starlight (Forge) (by Spottedstar)
Balm (Forge Edition) (by BlayTheNinth)
Do a Barrel Roll (by enjarai)
Delightful (by brdbrn)
Monster Plus (by Nitespring)
Awesome Dungeon Ocean edition - Forge (by jtl_elisa)
Ars Creo (by baileyholl2)
Upgraded Core (by Rolfmao25)
Collective (by Serilum)
Roamers (by kitkait2001)
YUNG's Bridges (Forge) (by YUNGNICKYOUNG)
Thermal Locomotion (by TeamCoFH)
Konkrete [Forge] (by Keksuccino)
Server Tab Info (by black_dog20)
Integrated Dungeons and Structures (by CraisinLord)
Macaw's Windows (by sketch_macaw)
Resourceful Lib (by ThatGravyBoat)
Horse Expert (by Fuzs)
AutoRegLib (by Vazkii)
Controlling (by Jaredlll08)
Dungeons Enhanced (by Valarauko9)
Botarium (by CodexAdrian)
CoFH Core (by TeamCoFH)
Dungeons Libraries (by Patrigan)
Critters and Companions (by joosh_7889)
Gnumus Settlement (by mongoose_artist)
When Dungeons Arise - Forge! (by Aureljz)
Awesome Dungeon Nether edition - Forge (by jtl_elisa)
Saturn (by AbdElAziz333)
Structory (by botanydev)
Vampirism Integrations (by maxanier)
MrCrayfish's Furniture Mod (by MrCrayfish)
Vampirism - Become a vampire! (by maxanier)
Naturalist (by Starfish_Studios)
Overweight Farming (by agentmhkskg)
Obscure API (by ObscuriaOfficial)
Guard Villagers (by almightytallestred)
Bow Infinity Fix (Forge/Fabric) (by Parker8283)
Structure Gel API (by ModdingLegacy)
Create: Extended Flywheels (by Rabbitminers)
Ceiling Torch (by bl4ckscor3)
Curios API (Forge) (by TheIllusiveC4)
Library Ferret - Forge (by jtl_elisa)
More Minecarts and Rails (by goldey3)
Create Cafe (by 1mphuls3)
Infernal Expansion (by InfernalStudios)
FastSuite (by Shadows_of_Fire)
ChoiceTheorem's Overhauled Village (by ChoiceTheorem)
The Abyss II - The Other Side (by y4z0n)
Forbidden and Arcanus (by cesar_zorak)
Transparent (by Trikzon)
Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)
FTB Library (Forge) (by FTB)
Enchantment Descriptions (by DarkhaxDev)
CorgiLib (by Corgi_Taco)
FerriteCore (Forge) (by malte0811)
Resourceful Config (by ThatGravyBoat)
Upgrade Aquatic (by TeamAbnormals)
SwingThroughGrass (by exidex)
AppleSkin (by squeek502)
Paintings ++ (by AbsolemJackdaw)
Cultural Delights (by NCP_Bails)
Alternate Current (by SpaceWalkerRS)
Too Many Glyphs (by derringercubed)
Cloth Config API (Fabric/Forge) (by shedaniel)
Aquamirae (by ObscuriaOfficial)
Born in Chaos (by mongoose_artist)
Patchouli (by Vazkii)
Thermal Cultivation (by TeamCoFH)
Structure Essentials[Forge/Fabric] (by someaddon)
Red’s More Structures [Fabric & Forge] (by redstone3game)
Thermal Innovation (by TeamCoFH)
Create Stuff & Additions (by Furti_Two)
It Takes a Pillage (by izofar)
Canary (by AbdElAziz333)
Sophisticated Backpacks (by P3pp3rF1y)
Configured (by MrCrayfish)
Supplementaries (by MehVahdJukaar)
No Chat Reports (by Aizistral)
Food Effect Tooltips (Forge) (by Suel_ki)
AIOT Botania (by MelanX)
Create (by simibubi)
Iceberg [Forge] (by Grend_G)
Alex's Delight (by NCP_Bails)
Ars Nouveau (by baileyholl2)
Jade 🔍 (by Snownee_)
Stack Refill (by Serilum)
Pumpkillager's Quest (by Serilum)
Ars Omega (by dkmk100_ludum_dare)
Farmer's Respite (by lumpazl)
GeckoLib (by Gecko)
Smarter Farmers (farmers replant) (by MehVahdJukaar)
Ad Astra (by AlexNijjar)
Upgraded Netherite (by Rolfmao25)
The Conjurer (by ModdingLegacy)
Macaw's Paintings (by sketch_macaw)
Extra Golems (by skyjay1)
Stay Warm Together (by skyjay1)
SuperMartijn642's Core Lib (by SuperMartijn642)
Primordial Dictionary (by portakalcevheri)
Bygone Nether (by izofar)
Sky Villages [Forge] (by y4z0n)
Just Zoom [Forge] (by Keksuccino)
Nourished Nether (by MuffinsQw)
L_Ender 's Cataclysm (by mcl_ender)
ShulkerBoxTooltip [Fabric/Forge] (by MisterPeModder)
Another Furniture (by Starfish_Studios)
FastFurnace (by Shadows_of_Fire)
The Lost Castle (by jack_bagel)
Dungeons Gear (by the_infamous_1)
ConnectedTexturesMod (by tterrag1098)
Ars Elemental (by Alexth99)
Chunk Sending[Forge/Fabric] (by someaddon)
Traveler's Backpack (by Tiviacz1337)
YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)
End Remastered (by jack_bagel)
Advent of Ascension (Nevermine) (by Scimiguy)
Thermal Expansion (by TeamCoFH)
Explorify – Dungeons & Structures (by bebebea_loste)
Nether's Exoticism (by Furti_Two)
FTB Essentials (Forge) (by FTB)
Pluto (by AbdElAziz333)
FixMySpawnR (by AbsolemJackdaw)
Pyromancer (by nikgub_)
Thermal Dynamics (by TeamCoFH)
Variety Aquatic (by texboobcat)
Ad Astra!: Giselle Addon (by 지젤쟝다)
You've Goat to be Kidding Me! (by plantspookable)
Castle in the Sky (by songxia23)
Corpse (by henkelmax)
JourneyMap (by techbrew)
Relics (by SSKirillSS)
Simple Hats (by fonnymunkey)
Radon (by Asek3)
Thermal Integration (by TeamCoFH)
Valhelsia Core (by ValhelsiaTeam)
More Villagers (by SameDifferent)
Create Big Cannons (by rbasamoyai)
Towns and Towers (by Biban_Auriu)
Puzzles Lib [Forge & Fabric] (by Fuzs)
Connectivity[Forge/Fabric] (by someaddon)

**Comment by Y3Z0N** [comment]
we are aware of this issue and will ship an fix soon

**Comment by Yubiiiii** [comment]
Im having the same issue any date you can give us, like when it will be fixed?

**Comment by itsdinkd** [comment]
> we are aware of this issue and will ship an fix soon

eta?

**Comment by Y3Z0N** [comment]
fixed

**Comment by artekote** [comment]
You have to install the geckolib mod. I don't understand why it is not documented that it has such dependency
https://www.curseforge.com/minecraft/mc-mods/geckolib
