### ISSUE TITLE
Causes io.netty.handler error when trying to join servers or have anyone join yours

### ISSUE THREAD

**Issue by Devilswarchild** [Y3Z0N/theabyss#93]
### Describe the Bug

ok I pretty much had to nail this down by watching the log and caught it by chance when I was trying to diagnose it thorugh the help of redditors while reading an article on reader index write stuff by the io.netty.handler and at that time noticed the "channel" list of mods I was usingthat had networking code. so I started turning them off one by one and trying to join a test server. everytime I kept getting a "io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(12) + length(1) exceeds writerIndex(12): PooledUnsafeDirectByteBuf(ridx: 12, widx: 12, cap: 12)" error. suffice to say it was stressing me out. but I have found the culprit (im sure it wasn't your fault) and am now here.

### Reproduction Steps

1. make a modpack with the modlist I have given while including the abyss 2 (all mods are current release versions)
2. try to join a server (I used test.prisonfun.com)

### Expected Result

wasnt expecting any issues seeing as it works perfectly fine in singleplayer.

### Crash Report or Log

https://gist.github.com/Devilswarchild/aa745f7fb96a5d2b466ad1be6794e5e8

### Operating System

Windows 11

### Mod Version

1.9.X or older

### Minecraft Version

1.19.2

### Forge Version

43.2.8

### Other Mods

[Music Duration Reducer (by LudoCrypt)](https://www.curseforge.com/minecraft/mc-mods/music-duration-reducer)
[Re-chiseled (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/rechiseled)
[Cataclysm Weaponery (by eyezlevrai)](https://www.curseforge.com/minecraft/mc-mods/cataclysmweaponery)
[Scaling Health (by SilentChaos512)](https://www.curseforge.com/minecraft/mc-mods/scaling-health)
[Cave Spelunking[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/caveore)
[Move Plus (by Corosus)](https://www.curseforge.com/minecraft/mc-mods/move-plus)
[Awesome Dungeon - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-forge)
[Delightful (by brnbrd)](https://www.curseforge.com/minecraft/mc-mods/delightful)
[Epic Knights: Shields, Armor and Weapons [Fabric & Forge] (by magistu_)](https://www.curseforge.com/minecraft/mc-mods/epic-knights-armor-and-weapons)
[Mekanism Additions (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-additions)
[Copper Drops (by brnbrd)](https://www.curseforge.com/minecraft/mc-mods/copper-drops)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[Immersive structures (by ChoiceTheorem)](https://www.curseforge.com/minecraft/mc-mods/immersive-structures)
[Pam's HarvestCraft 2 - Trees (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-trees)
[Mekanism Generators (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-generators)
[Shadowlands (by dreamcritting)](https://www.curseforge.com/minecraft/mc-mods/shadowlands)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[The Graveyard (FORGE) (by finallion_13)](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-forge)
[Smooth Boot (Reloaded) (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/smooth-boot-reloaded)
[Signpost (by Gollorum)](https://www.curseforge.com/minecraft/mc-mods/signpost)
[BlockUI (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/blockui)
[Why stacks of 16? (by LaidBackSloth42)](https://www.curseforge.com/minecraft/mc-mods/why-stacks-of-16)
[Physics Mod (by haubna)](https://www.curseforge.com/minecraft/mc-mods/physics-mod)
[Library Ferret - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/library-ferret-forge)
[Better Fishing Rods (by TrueRealCursed_Warrior)](https://www.curseforge.com/minecraft/mc-mods/better-fishing-rods)
[Immersive Armors [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-armors)
[Pam's HarvestCraft 2 - Food Extended (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-extended)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Cull Leaves (by Motschen)](https://www.curseforge.com/minecraft/mc-mods/cull-leaves)
[Not Enough Crashes (Forge) (by NatanFudge)](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes-forge)
[Neat (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/neat)
[Spoorn Weapon Attributes [Fabric/Forge] (by spoorn)](https://www.curseforge.com/minecraft/mc-mods/spoorn-weapon-attributes)
[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
[Macaw's Windows (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-windows)
[Clickable advancements[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/clickable-advancements)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[AttributeFix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/attributefix)
[Modern Elevators and Escalators (by jonafanho)](https://www.curseforge.com/minecraft/mc-mods/modern-elevators-and-escalators)
[Valhelsia Core (by ValhelsiaTeam)](https://www.curseforge.com/minecraft/mc-mods/valhelsia-core)
[Better Fps - Render Distance[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance)
[Shield mechanics (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/shield-mechanics)
[Deeper and Darker (by KyaniteMods)](https://www.curseforge.com/minecraft/mc-mods/deeperdarker)
[Creeper Overhaul (by joosh_7889)](https://www.curseforge.com/minecraft/mc-mods/creeper-overhaul)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[Memory Settings[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/memory-settings)
[The Twilight Forest (by Benimatic)](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)
[Spoorn Armor Attributes [Fabric/Forge] (by spoorn)](https://www.curseforge.com/minecraft/mc-mods/spoorn-armorattributes)
[MC Story Mode Armors [Forge / Fabric] (by chronos_sacaria)](https://www.curseforge.com/minecraft/mc-mods/mcsa)
[Forbidden and Arcanus (by cesar_zorak)](https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus)
[Wormhole (Portals) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/wormhole-portals)
[One Twenty 1.20 Backport (by kleiders3010)](https://www.curseforge.com/minecraft/mc-mods/one-twenty-backport)
[Skin Layers 3D (Fabric/Forge) (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d)
[Silent Lib (silentlib) (by SilentChaos512)](https://www.curseforge.com/minecraft/mc-mods/silent-lib)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Simply Light (by Flanks255)](https://www.curseforge.com/minecraft/mc-mods/simply-light)
[Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
[Many Advancements (by ph5r0)](https://www.curseforge.com/minecraft/mc-mods/more_advancements)
[Basic Nether Ores [Forge/Fabric] (by cScotPlay)](https://www.curseforge.com/minecraft/mc-mods/basic-nether-ores)
[Aquaculture 2 (by Shadow)](https://www.curseforge.com/minecraft/mc-mods/aquaculture)
[Loot Integrations[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/loot-integrations)
[Iris & Oculus Flywheel Compat (by leon_mout)](https://www.curseforge.com/minecraft/mc-mods/iris-flywheel-compat)
[Botania (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/botania)
[Goblin Traders (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/goblin-traders)
[Polymorph (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/polymorph)
[Savage Ender Dragon[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/savage-ender-dragon)
[Infused Foods (by ApexMdr)](https://www.curseforge.com/minecraft/mc-mods/infused-foods)
[Biome Music[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/biome-music)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[MCglTF (by protoxy22)](https://www.curseforge.com/minecraft/mc-mods/mcgltf)
[Better Combat [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)
[Silent Gear (by SilentChaos512)](https://www.curseforge.com/minecraft/mc-mods/silent-gear)
[Portable Crafting Table (by 00theblackwolf00)](https://www.curseforge.com/minecraft/mc-mods/portable-crafting-table)
[GUI Scale[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/tip-the-gui)
[Star Wars Planets Ad Astra! (by TathanDev)](https://www.curseforge.com/minecraft/mc-mods/star-wars-planets-ad-astra)
[Structurize (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/structurize)
[Extreme Reactors (by ZeroNoRyouki)](https://www.curseforge.com/minecraft/mc-mods/extreme-reactors)
[Corail Woodcutter (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-woodcutter)
[WFC Waffles For Croptopia (by thehyvis)](https://www.curseforge.com/minecraft/mc-mods/wfc-waffles-for-croptopia)
[FastWorkbench (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastworkbench)
[Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)](https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge)
[Limited Chunkloading[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/limited-chunkloading)
[The Undergarden (by Quek04)](https://www.curseforge.com/minecraft/mc-mods/the-undergarden)
[Awesome Dungeon Nether edition - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-nether-forge)
[Patterned Glass (by thenamesnano)](https://www.curseforge.com/minecraft/mc-mods/patterned-glass)
[Packed Up (Backpacks) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/packed-up-backpacks)
[Naturalist (by Starfish_Studios)](https://www.curseforge.com/minecraft/mc-mods/naturalist)
[Structure Essentials[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/structure-essentials-forge-fabric)
[Custom Portal API [Forge] (by mysticpasta1)](https://www.curseforge.com/minecraft/mc-mods/custom-portal-api-forge)
[MVS - Moog's Voyager Structures (by finndog_123)](https://www.curseforge.com/minecraft/mc-mods/moogs-voyager-structures)
[The One Probe (by McJty)](https://www.curseforge.com/minecraft/mc-mods/the-one-probe)
[Additional Lanterns (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/additional-lanterns)
[ForgeEndertech (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/forgeendertech)
[Ad Astra!: Giselle Addon (by 지젤쟝다)](https://www.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[ViesCraft Machines (by Vies)](https://www.curseforge.com/minecraft/mc-mods/viescraft-airships)
[Curios API (Forge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)
[Croptopia (by thethonk)](https://www.curseforge.com/minecraft/mc-mods/croptopia)
[Atlantis (by mysticpasta1)](https://www.curseforge.com/minecraft/mc-mods/atlantis)
[AmbientSounds 5 (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/ambientsounds)
[Spice of Life: Carrot Edition (by lordcazsius)](https://www.curseforge.com/minecraft/mc-mods/spice-of-life-carrot-edition)
[Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[Configured (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/configured)
[Create Ad Astra Compat (by ssm227)](https://www.curseforge.com/minecraft/mc-mods/create-ad-astra-compat)
[Almost Unified (by AlmostReliable)](https://www.curseforge.com/minecraft/mc-mods/almost-unified)
[Hourglass (by DuckyCrayfish)](https://www.curseforge.com/minecraft/mc-mods/hourglass)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Death Counter (Forge) (by ohaiiChun)](https://www.curseforge.com/minecraft/mc-mods/death-counter)
[Apotheosis (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/apotheosis)
[Prefab (by wiggles_gaming)](https://www.curseforge.com/minecraft/mc-mods/prefab)
[Player Companions (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/player-companions)
[Awesome Dungeon Ocean edition - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-edition-ocean-forge)
[Iceberg [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/iceberg)
[Corail Pillar (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-pillar)
[Domum Ornamentum (by OrionOnline)](https://www.curseforge.com/minecraft/mc-mods/domum-ornamentum)
[Fastload (by StockiesLad)](https://www.curseforge.com/minecraft/mc-mods/fastload)
[The Abyss II - The Other Side (by y4z0n)](https://www.curseforge.com/minecraft/mc-mods/the-abyss-chapter-ii)
[Corpse (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/corpse)
[Ad Astra (by AlexNijjar)](https://www.curseforge.com/minecraft/mc-mods/ad-astra)
[FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Security Craft (by Geforce132)](https://www.curseforge.com/minecraft/mc-mods/security-craft)
[Cooking for Blockheads (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads)
[Better Villages - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/better-village-forge)
[Additional Structures (by XxRexRaptorxX)](https://www.curseforge.com/minecraft/mc-mods/additional-structures)
[Immersive Portals (for Forge) (by qouteall)](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-for-forge)
[Dense Ores - Abundant! (by NewJumperr)](https://www.curseforge.com/minecraft/mc-mods/dense-ores-abundant)
[Chunk Sending[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/chunk-sending-forge-fabric)
[Advancement Plaques [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/advancement-plaques)
[ZeroCore 2 (by ZeroNoRyouki)](https://www.curseforge.com/minecraft/mc-mods/zerocore)
[Oh The Biomes You'll Go (by AOCAWOL)](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)
[Enhanced Farming (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/enhanced-farming)
[Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
[Structure Gel API (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/structure-gel-api)
[Longer Login Times (by Dremoline)](https://www.curseforge.com/minecraft/mc-mods/longer-login-times)
[Magnesium/Rubidium Dynamic Lights (by TeamDeusVult)](https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged)
[Large Ore Deposits (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/large-ore-deposits)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[Mekanism Tools (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism-tools)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Infernal Expansion (by InfernalStudios)](https://www.curseforge.com/minecraft/mc-mods/infernal-expansion)
[Macaw's Paths and Pavings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paths-and-pavings)
[Catalogue (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/catalogue)
[Brutal Bosses - Dungeon Bosses (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/brutal-bosses-dungeon)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[Mekanism (by bradyaidanc)](https://www.curseforge.com/minecraft/mc-mods/mekanism)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[PlayerRevive (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/playerrevive)
[Block Limit Fix (by tropheusj)](https://www.curseforge.com/minecraft/mc-mods/block-limit-fix)
[Dynamic View[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/dynamic-view)
[Pam's HarvestCraft 2 - Crops (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-crops)
[Plantable Ores (by Vuserr)](https://www.curseforge.com/minecraft/mc-mods/plantable-ores)
[Farsight [Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/farsight)
[Fish of Thieves (by SteveKunG)](https://www.curseforge.com/minecraft/mc-mods/fish-of-thieves)
[Copperized (by brnbrd)](https://www.curseforge.com/minecraft/mc-mods/copperized)
[Twilight Forest: The Lost Blocks (by Kitteh6660)](https://www.curseforge.com/minecraft/mc-mods/twilight-forest-the-lost-blocks)
[Basic End Ores [Forge/Fabric] (by cScotPlay)](https://www.curseforge.com/minecraft/mc-mods/basic-end-ores)
[Yeetus Experimentus (by Sunekaer)](https://www.curseforge.com/minecraft/mc-mods/yeetusexperimentus)
[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
[Towns and Towers (by Biban_Auriu)](https://www.curseforge.com/minecraft/mc-mods/towns-and-towers)
[ESSENTIAL Mod (by SparkUniverse_)](https://www.curseforge.com/minecraft/mc-mods/essential-mod)
[Pam's HarvestCraft 2 - Food Core (by pamharvestcraft)](https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-core)
[Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)
[Ulterlands: Worlds Apart (by Zoruk_Mods)](https://www.curseforge.com/minecraft/mc-mods/the-ulterlands)
[Advancements Tracker and Overview (by Kaworru)](https://www.curseforge.com/minecraft/mc-mods/advancements-tracker)
[Reap Mod (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/reap-mod)
[Jade Addons (Forge) (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade-addons)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Colored Bricks Mod (by pinary_pi)](https://www.curseforge.com/minecraft/mc-mods/colored-bricks-mod)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Vanilla Plus Tools (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/vanilla-tools)
[Flywheel (by jozufozu)](https://www.curseforge.com/minecraft/mc-mods/flywheel)
[Multi-Piston (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/multi-piston)
[Stylecolonies (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/stylecolonies)
[Create Compats (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/create-compats)
[Farmer's Compats (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/farmers-compats)
[Resourceful Config (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-config)
[Awesome Dungeon The End edition - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-the-end-forge)
[When Dungeons Arise - Forge! (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise)
[Forgiving World - Dimension Stacking[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/forgiving-world)
[Double Doors (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/double-doors)
[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Medieval Music[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/medieval-music)
[Croptopia Additions (by Numerosityy)](https://www.curseforge.com/minecraft/mc-mods/croptopia-additions)
[Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts)
[Inventory Sorter (by cpw)](https://www.curseforge.com/minecraft/mc-mods/inventory-sorter)
[VR Library (by Vuserr)](https://www.curseforge.com/minecraft/mc-mods/vr-library)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Botania: Garden of Glass (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/botania-garden-of-glass)
[The Lost Cities (by McJty)](https://www.curseforge.com/minecraft/mc-mods/the-lost-cities)
[Dragon Mounts: Legacy (by UnitKay9)](https://www.curseforge.com/minecraft/mc-mods/dragon-mounts-legacy)
[Login Protection[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/login-protection)
[Unstructured [Fabric/Forge] (by Cristelknight)](https://www.curseforge.com/minecraft/mc-mods/unstructured)
[MineColonies (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/minecolonies)
[Botarium (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/botarium)
[Magnesium/Rubidium Extras (by TeamDeusVult)](https://www.curseforge.com/minecraft/mc-mods/magnesium-extras)
[Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[FallingTree (Forge&Fabric) (by rakambda)](https://www.curseforge.com/minecraft/mc-mods/falling-tree)
[The Lost Castle (by jack_bagel)](https://www.curseforge.com/minecraft/mc-mods/the-lost-castle)
[Placebo (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/placebo)
[Blue Skies (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/blue-skies)
[Oreberries Replanted (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/oreberries-replanted)
[FastFurnace (by Shadows_of_Fire)](https://www.curseforge.com/minecraft/mc-mods/fastfurnace)
[L_Ender 's Cataclysm (by mcl_ender)](https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm)
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[SecretRoomsMod (by AbrarSyed)](https://www.curseforge.com/minecraft/mc-mods/secretroomsmod)
[Storage Racks (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/storage-racks)
[Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
[TrashSlot (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/trashslot)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)

### Additional Context

the error literally stopped once I disabled your mod.

**Comment by Devilswarchild** [comment]
it also gives a malformed byte at byte " insert random number/ last number it gave me was 104" when I tried to join either my partners world or her joining mine. so there is something definitely going on with this mod in relation to networking of some kind.

**Comment by Y3Z0N** [comment]
fixed

**Comment by Devilswarchild** [comment]
sweet, thank you very much. I can now update the mod pack with the latest version of this mod and re-enable it for my downloaders to enjoy
