### ISSUE TITLE
Abyss 2 crashing on server side, but not client.

### ISSUE THREAD

**Issue by Fuvias** [Y3Z0N/theabyss#95]
### Describe the Bug

Crashes the server, as it fails to load properly for 1.19.2 modpacks and the sort.

### Reproduction Steps

a

### Expected Result

THe server loads properly.

### Operating System

windows 11

### Mod Version

1.9.X or older

### Minecraft Version

1.19.2

### Forge Version

36.2.20

**Comment by YukiRainee** [comment]
same issue here using latest forge 43.2.11
[crash-2023-05-14_07.29.28-fml.txt](https://github.com/Y3Z0N/theabyss/files/11471366/crash-2023-05-14_07.29.28-fml.txt)

**Comment by Ryuushen** [comment]
Same thing happened. Can't start on server

**Comment by Y3Z0N** [comment]
fixed
