### ISSUE TITLE
Structure and Broken radio missing 

### ISSUE THREAD

**Issue by Mau-Jr** [Y3Z0N/theabyss#96]
### Describe the Bug

Abandoned house structure doesn’t exist, as well as Broken radio item

### Reproduction Steps

Search for them on JEI and /locate command

### Expected Result

Item and structure to be there

### Operating System

Windows 10

### Mod Version

1.9.X or older

### Minecraft Version

1.19.2

### Forge Version

43.2.3

**Comment by Y3Z0N** [comment]
it was removed on purpose read the guidebook please.
