### ISSUE TITLE
Client and server crash on start

### ISSUE THREAD

**Issue by ulises-aragon** [Y3Z0N/theabyss#97]
### Describe the Bug

Whenever I start my modded server or my client game, as soon as the mods start to load, Minecraft crashes and it throws an error pointing to The Abyss mod.

### Reproduction Steps

Use the same mod version with Forge 43.2.13 and start the game.

### Expected Result

Mods loading correctly and game/server normal execution.

### Crash Report or Log

https://pastebin.com/LwT45j1e

### Operating System

Windows 10

### Mod Version

1.9.X or older

### Minecraft Version

1.19.2

### Forge Version

43.2.13

### Additional Context

The crash log seems to be the same in the server and the client

**Comment by Y3Z0N** [comment]
use GeckoLib. then it should start
