### ISSUE TITLE
crystal shards unobtainable because crystal cutter does not work

### ISSUE THREAD

**Issue by puncix** [Y3Z0N/theabyss#99]
### Describe the Bug

crystal cutter eats the crystal and loran energy but does not produce the crystal shard in 1.19.2

### Reproduction Steps

1.use the crystal cutter

### Expected Result

production of crystal shard

### Operating System

windows 10

### Mod Version

2.2.2

### Minecraft Version

1.19.2

### Forge Version

43.2.10

### Additional Context

crystal cutting recipe is missing from jei too

**Comment by Correlander** [comment]
You need to research the crystal first, this isn't a bug.

**Comment by Y3Z0N** [comment]
Cutter works great. you just haven researched crystals on a research table
